// Graywolf modem ↔ application IPC protocol.
//
// Wire format: length-prefixed IpcMessage frames over a Unix domain socket.
// Each frame is [4 bytes big-endian length][IpcMessage protobuf bytes].
//
// All messages are wrapped in the IpcMessage oneof envelope so that a single
// bidirectional stream can carry both directions without a separate type tag.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: graywolf.proto

package ipcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioDeviceKind int32

const (
	AudioDeviceKind_AUDIO_DEVICE_KIND_UNSPECIFIED AudioDeviceKind = 0
	AudioDeviceKind_AUDIO_DEVICE_KIND_INPUT       AudioDeviceKind = 1
	AudioDeviceKind_AUDIO_DEVICE_KIND_OUTPUT      AudioDeviceKind = 2
)

// Enum value maps for AudioDeviceKind.
var (
	AudioDeviceKind_name = map[int32]string{
		0: "AUDIO_DEVICE_KIND_UNSPECIFIED",
		1: "AUDIO_DEVICE_KIND_INPUT",
		2: "AUDIO_DEVICE_KIND_OUTPUT",
	}
	AudioDeviceKind_value = map[string]int32{
		"AUDIO_DEVICE_KIND_UNSPECIFIED": 0,
		"AUDIO_DEVICE_KIND_INPUT":       1,
		"AUDIO_DEVICE_KIND_OUTPUT":      2,
	}
)

func (x AudioDeviceKind) Enum() *AudioDeviceKind {
	p := new(AudioDeviceKind)
	*p = x
	return p
}

func (x AudioDeviceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioDeviceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_graywolf_proto_enumTypes[0].Descriptor()
}

func (AudioDeviceKind) Type() protoreflect.EnumType {
	return &file_graywolf_proto_enumTypes[0]
}

func (x AudioDeviceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioDeviceKind.Descriptor instead.
func (AudioDeviceKind) EnumDescriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{0}
}

type IpcMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*IpcMessage_ReceivedFrame
	//	*IpcMessage_DcdChange
	//	*IpcMessage_StatusUpdate
	//	*IpcMessage_ModemReady
	//	*IpcMessage_AudioDeviceList
	//	*IpcMessage_DeviceLevelUpdate
	//	*IpcMessage_InputLevelScanResult
	//	*IpcMessage_TestSignalResult
	//	*IpcMessage_TransmitFrame
	//	*IpcMessage_ConfigureChannel
	//	*IpcMessage_ConfigureAudio
	//	*IpcMessage_ConfigurePtt
	//	*IpcMessage_StartAudio
	//	*IpcMessage_StopAudio
	//	*IpcMessage_Shutdown
	//	*IpcMessage_EnumerateAudioDevices
	//	*IpcMessage_SetDeviceGain
	//	*IpcMessage_ScanInputLevels
	//	*IpcMessage_ManualPtt
	//	*IpcMessage_TransmitTestSignal
	Payload       isIpcMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpcMessage) Reset() {
	*x = IpcMessage{}
	mi := &file_graywolf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcMessage) ProtoMessage() {}

func (x *IpcMessage) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcMessage.ProtoReflect.Descriptor instead.
func (*IpcMessage) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{0}
}

func (x *IpcMessage) GetPayload() isIpcMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IpcMessage) GetReceivedFrame() *ReceivedFrame {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_ReceivedFrame); ok {
			return x.ReceivedFrame
		}
	}
	return nil
}

func (x *IpcMessage) GetDcdChange() *DcdChange {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_DcdChange); ok {
			return x.DcdChange
		}
	}
	return nil
}

func (x *IpcMessage) GetStatusUpdate() *StatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_StatusUpdate); ok {
			return x.StatusUpdate
		}
	}
	return nil
}

func (x *IpcMessage) GetModemReady() *ModemReady {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_ModemReady); ok {
			return x.ModemReady
		}
	}
	return nil
}

func (x *IpcMessage) GetAudioDeviceList() *AudioDeviceList {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_AudioDeviceList); ok {
			return x.AudioDeviceList
		}
	}
	return nil
}

func (x *IpcMessage) GetDeviceLevelUpdate() *DeviceLevelUpdate {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_DeviceLevelUpdate); ok {
			return x.DeviceLevelUpdate
		}
	}
	return nil
}

func (x *IpcMessage) GetInputLevelScanResult() *InputLevelScanResult {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_InputLevelScanResult); ok {
			return x.InputLevelScanResult
		}
	}
	return nil
}

func (x *IpcMessage) GetTestSignalResult() *TestSignalResult {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_TestSignalResult); ok {
			return x.TestSignalResult
		}
	}
	return nil
}

func (x *IpcMessage) GetTransmitFrame() *TransmitFrame {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_TransmitFrame); ok {
			return x.TransmitFrame
		}
	}
	return nil
}

func (x *IpcMessage) GetConfigureChannel() *ConfigureChannel {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_ConfigureChannel); ok {
			return x.ConfigureChannel
		}
	}
	return nil
}

func (x *IpcMessage) GetConfigureAudio() *ConfigureAudio {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_ConfigureAudio); ok {
			return x.ConfigureAudio
		}
	}
	return nil
}

func (x *IpcMessage) GetConfigurePtt() *ConfigurePtt {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_ConfigurePtt); ok {
			return x.ConfigurePtt
		}
	}
	return nil
}

func (x *IpcMessage) GetStartAudio() *StartAudio {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_StartAudio); ok {
			return x.StartAudio
		}
	}
	return nil
}

func (x *IpcMessage) GetStopAudio() *StopAudio {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_StopAudio); ok {
			return x.StopAudio
		}
	}
	return nil
}

func (x *IpcMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *IpcMessage) GetEnumerateAudioDevices() *EnumerateAudioDevices {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_EnumerateAudioDevices); ok {
			return x.EnumerateAudioDevices
		}
	}
	return nil
}

func (x *IpcMessage) GetSetDeviceGain() *SetDeviceGain {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_SetDeviceGain); ok {
			return x.SetDeviceGain
		}
	}
	return nil
}

func (x *IpcMessage) GetScanInputLevels() *ScanInputLevels {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_ScanInputLevels); ok {
			return x.ScanInputLevels
		}
	}
	return nil
}

func (x *IpcMessage) GetManualPtt() *ManualPtt {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_ManualPtt); ok {
			return x.ManualPtt
		}
	}
	return nil
}

func (x *IpcMessage) GetTransmitTestSignal() *TransmitTestSignal {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_TransmitTestSignal); ok {
			return x.TransmitTestSignal
		}
	}
	return nil
}

type isIpcMessage_Payload interface {
	isIpcMessage_Payload()
}

type IpcMessage_ReceivedFrame struct {
	// Rust modem → Go application
	ReceivedFrame *ReceivedFrame `protobuf:"bytes,1,opt,name=received_frame,json=receivedFrame,proto3,oneof"`
}

type IpcMessage_DcdChange struct {
	DcdChange *DcdChange `protobuf:"bytes,2,opt,name=dcd_change,json=dcdChange,proto3,oneof"`
}

type IpcMessage_StatusUpdate struct {
	StatusUpdate *StatusUpdate `protobuf:"bytes,3,opt,name=status_update,json=statusUpdate,proto3,oneof"`
}

type IpcMessage_ModemReady struct {
	ModemReady *ModemReady `protobuf:"bytes,4,opt,name=modem_ready,json=modemReady,proto3,oneof"`
}

type IpcMessage_AudioDeviceList struct {
	AudioDeviceList *AudioDeviceList `protobuf:"bytes,5,opt,name=audio_device_list,json=audioDeviceList,proto3,oneof"`
}

type IpcMessage_DeviceLevelUpdate struct {
	DeviceLevelUpdate *DeviceLevelUpdate `protobuf:"bytes,7,opt,name=device_level_update,json=deviceLevelUpdate,proto3,oneof"`
}

type IpcMessage_InputLevelScanResult struct {
	InputLevelScanResult *InputLevelScanResult `protobuf:"bytes,8,opt,name=input_level_scan_result,json=inputLevelScanResult,proto3,oneof"`
}

type IpcMessage_TestSignalResult struct {
	TestSignalResult *TestSignalResult `protobuf:"bytes,9,opt,name=test_signal_result,json=testSignalResult,proto3,oneof"`
}

type IpcMessage_TransmitFrame struct {
	// Go application → Rust modem
	TransmitFrame *TransmitFrame `protobuf:"bytes,10,opt,name=transmit_frame,json=transmitFrame,proto3,oneof"`
}

type IpcMessage_ConfigureChannel struct {
	ConfigureChannel *ConfigureChannel `protobuf:"bytes,11,opt,name=configure_channel,json=configureChannel,proto3,oneof"`
}

type IpcMessage_ConfigureAudio struct {
	ConfigureAudio *ConfigureAudio `protobuf:"bytes,12,opt,name=configure_audio,json=configureAudio,proto3,oneof"`
}

type IpcMessage_ConfigurePtt struct {
	ConfigurePtt *ConfigurePtt `protobuf:"bytes,13,opt,name=configure_ptt,json=configurePtt,proto3,oneof"`
}

type IpcMessage_StartAudio struct {
	StartAudio *StartAudio `protobuf:"bytes,14,opt,name=start_audio,json=startAudio,proto3,oneof"`
}

type IpcMessage_StopAudio struct {
	StopAudio *StopAudio `protobuf:"bytes,15,opt,name=stop_audio,json=stopAudio,proto3,oneof"`
}

type IpcMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,16,opt,name=shutdown,proto3,oneof"`
}

type IpcMessage_EnumerateAudioDevices struct {
	EnumerateAudioDevices *EnumerateAudioDevices `protobuf:"bytes,17,opt,name=enumerate_audio_devices,json=enumerateAudioDevices,proto3,oneof"`
}

type IpcMessage_SetDeviceGain struct {
	SetDeviceGain *SetDeviceGain `protobuf:"bytes,19,opt,name=set_device_gain,json=setDeviceGain,proto3,oneof"`
}

type IpcMessage_ScanInputLevels struct {
	ScanInputLevels *ScanInputLevels `protobuf:"bytes,20,opt,name=scan_input_levels,json=scanInputLevels,proto3,oneof"`
}

type IpcMessage_ManualPtt struct {
	ManualPtt *ManualPtt `protobuf:"bytes,21,opt,name=manual_ptt,json=manualPtt,proto3,oneof"` // Go → Rust: manual PTT toggle for testing
}

type IpcMessage_TransmitTestSignal struct {
	TransmitTestSignal *TransmitTestSignal `protobuf:"bytes,22,opt,name=transmit_test_signal,json=transmitTestSignal,proto3,oneof"`
}

func (*IpcMessage_ReceivedFrame) isIpcMessage_Payload() {}

func (*IpcMessage_DcdChange) isIpcMessage_Payload() {}

func (*IpcMessage_StatusUpdate) isIpcMessage_Payload() {}

func (*IpcMessage_ModemReady) isIpcMessage_Payload() {}

func (*IpcMessage_AudioDeviceList) isIpcMessage_Payload() {}

func (*IpcMessage_DeviceLevelUpdate) isIpcMessage_Payload() {}

func (*IpcMessage_InputLevelScanResult) isIpcMessage_Payload() {}

func (*IpcMessage_TestSignalResult) isIpcMessage_Payload() {}

func (*IpcMessage_TransmitFrame) isIpcMessage_Payload() {}

func (*IpcMessage_ConfigureChannel) isIpcMessage_Payload() {}

func (*IpcMessage_ConfigureAudio) isIpcMessage_Payload() {}

func (*IpcMessage_ConfigurePtt) isIpcMessage_Payload() {}

func (*IpcMessage_StartAudio) isIpcMessage_Payload() {}

func (*IpcMessage_StopAudio) isIpcMessage_Payload() {}

func (*IpcMessage_Shutdown) isIpcMessage_Payload() {}

func (*IpcMessage_EnumerateAudioDevices) isIpcMessage_Payload() {}

func (*IpcMessage_SetDeviceGain) isIpcMessage_Payload() {}

func (*IpcMessage_ScanInputLevels) isIpcMessage_Payload() {}

func (*IpcMessage_ManualPtt) isIpcMessage_Payload() {}

func (*IpcMessage_TransmitTestSignal) isIpcMessage_Payload() {}

// A successfully decoded AX.25 frame with demodulator metadata.
type ReceivedFrame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Channel         uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`                                           // logical radio channel
	Subchan         uint32                 `protobuf:"varint,2,opt,name=subchan,proto3" json:"subchan,omitempty"`                                           // demodulator subchannel
	Slice           uint32                 `protobuf:"varint,3,opt,name=slice,proto3" json:"slice,omitempty"`                                               // slicer index
	Data            []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                                                  // AX.25 frame bytes, FCS stripped
	Quality         int32                  `protobuf:"varint,5,opt,name=quality,proto3" json:"quality,omitempty"`                                           // 0..100 decoder quality
	AudioLevelMark  float32                `protobuf:"fixed32,6,opt,name=audio_level_mark,json=audioLevelMark,proto3" json:"audio_level_mark,omitempty"`    // mark level at time of capture
	AudioLevelSpace float32                `protobuf:"fixed32,7,opt,name=audio_level_space,json=audioLevelSpace,proto3" json:"audio_level_space,omitempty"` // space level at time of capture
	SpeedError      float32                `protobuf:"fixed32,8,opt,name=speed_error,json=speedError,proto3" json:"speed_error,omitempty"`                  // baud-rate error, percent
	Retry           string                 `protobuf:"bytes,9,opt,name=retry,proto3" json:"retry,omitempty"`                                                // "none" | "single" | "double"
	TimestampNs     uint64                 `protobuf:"varint,10,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`               // monotonic capture time
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReceivedFrame) Reset() {
	*x = ReceivedFrame{}
	mi := &file_graywolf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedFrame) ProtoMessage() {}

func (x *ReceivedFrame) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedFrame.ProtoReflect.Descriptor instead.
func (*ReceivedFrame) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{1}
}

func (x *ReceivedFrame) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ReceivedFrame) GetSubchan() uint32 {
	if x != nil {
		return x.Subchan
	}
	return 0
}

func (x *ReceivedFrame) GetSlice() uint32 {
	if x != nil {
		return x.Slice
	}
	return 0
}

func (x *ReceivedFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReceivedFrame) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ReceivedFrame) GetAudioLevelMark() float32 {
	if x != nil {
		return x.AudioLevelMark
	}
	return 0
}

func (x *ReceivedFrame) GetAudioLevelSpace() float32 {
	if x != nil {
		return x.AudioLevelSpace
	}
	return 0
}

func (x *ReceivedFrame) GetSpeedError() float32 {
	if x != nil {
		return x.SpeedError
	}
	return 0
}

func (x *ReceivedFrame) GetRetry() string {
	if x != nil {
		return x.Retry
	}
	return ""
}

func (x *ReceivedFrame) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

// Data Carrier Detect state transition.
type DcdChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Subchan       uint32                 `protobuf:"varint,2,opt,name=subchan,proto3" json:"subchan,omitempty"`
	Slice         uint32                 `protobuf:"varint,3,opt,name=slice,proto3" json:"slice,omitempty"`
	Detected      bool                   `protobuf:"varint,4,opt,name=detected,proto3" json:"detected,omitempty"`
	TimestampNs   uint64                 `protobuf:"varint,5,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DcdChange) Reset() {
	*x = DcdChange{}
	mi := &file_graywolf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DcdChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DcdChange) ProtoMessage() {}

func (x *DcdChange) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DcdChange.ProtoReflect.Descriptor instead.
func (*DcdChange) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{2}
}

func (x *DcdChange) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *DcdChange) GetSubchan() uint32 {
	if x != nil {
		return x.Subchan
	}
	return 0
}

func (x *DcdChange) GetSlice() uint32 {
	if x != nil {
		return x.Slice
	}
	return 0
}

func (x *DcdChange) GetDetected() bool {
	if x != nil {
		return x.Detected
	}
	return false
}

func (x *DcdChange) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

// Periodic health / metrics update. Consumed by Go for Prometheus export.
type StatusUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Channel          uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	RxFrames         uint64                 `protobuf:"varint,2,opt,name=rx_frames,json=rxFrames,proto3" json:"rx_frames,omitempty"`
	RxBadFcs         uint64                 `protobuf:"varint,3,opt,name=rx_bad_fcs,json=rxBadFcs,proto3" json:"rx_bad_fcs,omitempty"`
	TxFrames         uint64                 `protobuf:"varint,4,opt,name=tx_frames,json=txFrames,proto3" json:"tx_frames,omitempty"`
	DcdTransitions   uint64                 `protobuf:"varint,5,opt,name=dcd_transitions,json=dcdTransitions,proto3" json:"dcd_transitions,omitempty"`
	AudioLevelMark   float32                `protobuf:"fixed32,6,opt,name=audio_level_mark,json=audioLevelMark,proto3" json:"audio_level_mark,omitempty"`
	AudioLevelSpace  float32                `protobuf:"fixed32,7,opt,name=audio_level_space,json=audioLevelSpace,proto3" json:"audio_level_space,omitempty"`
	AudioLevelPeak   float32                `protobuf:"fixed32,8,opt,name=audio_level_peak,json=audioLevelPeak,proto3" json:"audio_level_peak,omitempty"`
	DcdState         bool                   `protobuf:"varint,9,opt,name=dcd_state,json=dcdState,proto3" json:"dcd_state,omitempty"`
	ShutdownComplete bool                   `protobuf:"varint,10,opt,name=shutdown_complete,json=shutdownComplete,proto3" json:"shutdown_complete,omitempty"` // final status before process exit
	TimestampNs      uint64                 `protobuf:"varint,11,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_graywolf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{3}
}

func (x *StatusUpdate) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *StatusUpdate) GetRxFrames() uint64 {
	if x != nil {
		return x.RxFrames
	}
	return 0
}

func (x *StatusUpdate) GetRxBadFcs() uint64 {
	if x != nil {
		return x.RxBadFcs
	}
	return 0
}

func (x *StatusUpdate) GetTxFrames() uint64 {
	if x != nil {
		return x.TxFrames
	}
	return 0
}

func (x *StatusUpdate) GetDcdTransitions() uint64 {
	if x != nil {
		return x.DcdTransitions
	}
	return 0
}

func (x *StatusUpdate) GetAudioLevelMark() float32 {
	if x != nil {
		return x.AudioLevelMark
	}
	return 0
}

func (x *StatusUpdate) GetAudioLevelSpace() float32 {
	if x != nil {
		return x.AudioLevelSpace
	}
	return 0
}

func (x *StatusUpdate) GetAudioLevelPeak() float32 {
	if x != nil {
		return x.AudioLevelPeak
	}
	return 0
}

func (x *StatusUpdate) GetDcdState() bool {
	if x != nil {
		return x.DcdState
	}
	return false
}

func (x *StatusUpdate) GetShutdownComplete() bool {
	if x != nil {
		return x.ShutdownComplete
	}
	return false
}

func (x *StatusUpdate) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

// Sent once after the modem has bound its IPC socket, accepted a connection,
// and is ready to receive configuration messages.
type ModemReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Pid           uint64                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModemReady) Reset() {
	*x = ModemReady{}
	mi := &file_graywolf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModemReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModemReady) ProtoMessage() {}

func (x *ModemReady) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModemReady.ProtoReflect.Descriptor instead.
func (*ModemReady) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{4}
}

func (x *ModemReady) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModemReady) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// Response to EnumerateAudioDevices.
type AudioDeviceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Devices       []*AudioDeviceInfo     `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioDeviceList) Reset() {
	*x = AudioDeviceList{}
	mi := &file_graywolf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioDeviceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioDeviceList) ProtoMessage() {}

func (x *AudioDeviceList) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioDeviceList.ProtoReflect.Descriptor instead.
func (*AudioDeviceList) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{5}
}

func (x *AudioDeviceList) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *AudioDeviceList) GetDevices() []*AudioDeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type AudioDeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StableId      string                 `protobuf:"bytes,2,opt,name=stable_id,json=stableId,proto3" json:"stable_id,omitempty"` // stable identifier, or name if unavailable
	Kind          AudioDeviceKind        `protobuf:"varint,3,opt,name=kind,proto3,enum=graywolf.AudioDeviceKind" json:"kind,omitempty"`
	SampleRates   []uint32               `protobuf:"varint,4,rep,packed,name=sample_rates,json=sampleRates,proto3" json:"sample_rates,omitempty"`
	ChannelCounts []uint32               `protobuf:"varint,5,rep,packed,name=channel_counts,json=channelCounts,proto3" json:"channel_counts,omitempty"`
	HostApi       string                 `protobuf:"bytes,6,opt,name=host_api,json=hostApi,proto3" json:"host_api,omitempty"` // "CoreAudio", "ALSA", "WASAPI"
	IsDefault     bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`  // human-friendly name (e.g. USB product string)
	Recommended   bool                   `protobuf:"varint,9,opt,name=recommended,proto3" json:"recommended,omitempty"` // true for plughw: devices (ALSA software conversion)
	// Windows only: the endpoint has audio "enhancements" (system effects /
	// APOs) active. Those DSP effects mangle AFSK/packet audio and degrade
	// decoding, so the UI warns the operator. Always false on Linux/macOS.
	AudioEnhancementsEnabled bool `protobuf:"varint,10,opt,name=audio_enhancements_enabled,json=audioEnhancementsEnabled,proto3" json:"audio_enhancements_enabled,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AudioDeviceInfo) Reset() {
	*x = AudioDeviceInfo{}
	mi := &file_graywolf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioDeviceInfo) ProtoMessage() {}

func (x *AudioDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioDeviceInfo.ProtoReflect.Descriptor instead.
func (*AudioDeviceInfo) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{6}
}

func (x *AudioDeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AudioDeviceInfo) GetStableId() string {
	if x != nil {
		return x.StableId
	}
	return ""
}

func (x *AudioDeviceInfo) GetKind() AudioDeviceKind {
	if x != nil {
		return x.Kind
	}
	return AudioDeviceKind_AUDIO_DEVICE_KIND_UNSPECIFIED
}

func (x *AudioDeviceInfo) GetSampleRates() []uint32 {
	if x != nil {
		return x.SampleRates
	}
	return nil
}

func (x *AudioDeviceInfo) GetChannelCounts() []uint32 {
	if x != nil {
		return x.ChannelCounts
	}
	return nil
}

func (x *AudioDeviceInfo) GetHostApi() string {
	if x != nil {
		return x.HostApi
	}
	return ""
}

func (x *AudioDeviceInfo) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *AudioDeviceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AudioDeviceInfo) GetRecommended() bool {
	if x != nil {
		return x.Recommended
	}
	return false
}

func (x *AudioDeviceInfo) GetAudioEnhancementsEnabled() bool {
	if x != nil {
		return x.AudioEnhancementsEnabled
	}
	return false
}

// Request transmission of a raw AX.25 frame on a specific channel.
type TransmitFrame struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Channel           uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Data              []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                                       // AX.25 frame bytes, no FCS (modem appends)
	TxdelayOverrideMs uint32                 `protobuf:"varint,3,opt,name=txdelay_override_ms,json=txdelayOverrideMs,proto3" json:"txdelay_override_ms,omitempty"` // 0 = use configured default
	TxtailOverrideMs  uint32                 `protobuf:"varint,4,opt,name=txtail_override_ms,json=txtailOverrideMs,proto3" json:"txtail_override_ms,omitempty"`
	Priority          uint32                 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"` // higher = sooner
	// Monotonic correlation ID stamped at txgovernor.Governor.Submit (starts
	// at 1; zero = unstamped). Propagated through the dispatcher and every
	// TX backend for log correlation across partial-failure fan-outs.
	// Backward-compatible: older modems simply ignore the field.
	FrameId       uint64 `protobuf:"varint,6,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransmitFrame) Reset() {
	*x = TransmitFrame{}
	mi := &file_graywolf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransmitFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransmitFrame) ProtoMessage() {}

func (x *TransmitFrame) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransmitFrame.ProtoReflect.Descriptor instead.
func (*TransmitFrame) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{7}
}

func (x *TransmitFrame) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *TransmitFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TransmitFrame) GetTxdelayOverrideMs() uint32 {
	if x != nil {
		return x.TxdelayOverrideMs
	}
	return 0
}

func (x *TransmitFrame) GetTxtailOverrideMs() uint32 {
	if x != nil {
		return x.TxtailOverrideMs
	}
	return 0
}

func (x *TransmitFrame) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TransmitFrame) GetFrameId() uint64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

// Configure a logical radio channel's demodulator parameters.
type ConfigureChannel struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Channel        uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	DeviceId       uint32                 `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`             // audio device this channel reads from
	AudioChannel   uint32                 `protobuf:"varint,3,opt,name=audio_channel,json=audioChannel,proto3" json:"audio_channel,omitempty"` // 0=left / mono, 1=right
	Baud           uint32                 `protobuf:"varint,4,opt,name=baud,proto3" json:"baud,omitempty"`                                     // 1200, 2400, 4800, 9600
	MarkFreq       uint32                 `protobuf:"varint,5,opt,name=mark_freq,json=markFreq,proto3" json:"mark_freq,omitempty"`
	SpaceFreq      uint32                 `protobuf:"varint,6,opt,name=space_freq,json=spaceFreq,proto3" json:"space_freq,omitempty"`
	ModemType      string                 `protobuf:"bytes,7,opt,name=modem_type,json=modemType,proto3" json:"modem_type,omitempty"` // "afsk" (phase 1), "psk", "9600" later
	Profile        string                 `protobuf:"bytes,8,opt,name=profile,proto3" json:"profile,omitempty"`                      // "A" | "B"
	NumSlicers     uint32                 `protobuf:"varint,9,opt,name=num_slicers,json=numSlicers,proto3" json:"num_slicers,omitempty"`
	FixBits        string                 `protobuf:"bytes,10,opt,name=fix_bits,json=fixBits,proto3" json:"fix_bits,omitempty"`                         // "none" | "single" | "double"
	NumDecoders    uint32                 `protobuf:"varint,11,opt,name=num_decoders,json=numDecoders,proto3" json:"num_decoders,omitempty"`            // multi-modem: number of parallel decoders
	DecoderOffset  int32                  `protobuf:"varint,12,opt,name=decoder_offset,json=decoderOffset,proto3" json:"decoder_offset,omitempty"`      // multi-modem: frequency offset step in Hz
	Fx25Encode     bool                   `protobuf:"varint,13,opt,name=fx25_encode,json=fx25Encode,proto3" json:"fx25_encode,omitempty"`               // enable FX.25 RS FEC on transmit
	Il2PEncode     bool                   `protobuf:"varint,14,opt,name=il2p_encode,json=il2pEncode,proto3" json:"il2p_encode,omitempty"`               // enable IL2P encoding on transmit
	InputDeviceId  uint32                 `protobuf:"varint,15,opt,name=input_device_id,json=inputDeviceId,proto3" json:"input_device_id,omitempty"`    // input audio device (replaces device_id)
	InputChannel   uint32                 `protobuf:"varint,16,opt,name=input_channel,json=inputChannel,proto3" json:"input_channel,omitempty"`         // input stereo select (replaces audio_channel)
	OutputDeviceId uint32                 `protobuf:"varint,17,opt,name=output_device_id,json=outputDeviceId,proto3" json:"output_device_id,omitempty"` // output audio device, 0 = RX-only
	OutputChannel  uint32                 `protobuf:"varint,18,opt,name=output_channel,json=outputChannel,proto3" json:"output_channel,omitempty"`      // output stereo select
	// Multi-demodulator ensemble preset for AFSK. Overrides `profile` and
	// `num_slicers` when it resolves to a multi-demod preset. Known values:
	//
	//	""        — default, treated as "triple" (recommended for all new
	//	            installs; matches or beats Direwolf -P AD+ on the
	//	            WA8LMF reference tracks, costs ~1.6% of one CPU core)
	//	"triple"  — RECOMMENDED_3DEMOD: Profile A ×9 slicers + A ×9 with
	//	            hard-limiter + Profile B ×9 slicers
	//	"dual"    — RECOMMENDED_2DEMOD: Profile A ×9 with and without HL
	//	"single"  — explicit legacy single-demodulator path; respects
	//	            `profile` and `num_slicers`. Use when you need the
	//	            lowest possible CPU or want to reproduce old behavior.
	//
	// When a preset is active, output frames are deduped across the ensemble
	// using a 3-symbol time window (matching Direwolf's dedup semantics).
	DemodEnsemble string `protobuf:"bytes,19,opt,name=demod_ensemble,json=demodEnsemble,proto3" json:"demod_ensemble,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureChannel) Reset() {
	*x = ConfigureChannel{}
	mi := &file_graywolf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureChannel) ProtoMessage() {}

func (x *ConfigureChannel) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureChannel.ProtoReflect.Descriptor instead.
func (*ConfigureChannel) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigureChannel) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ConfigureChannel) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *ConfigureChannel) GetAudioChannel() uint32 {
	if x != nil {
		return x.AudioChannel
	}
	return 0
}

func (x *ConfigureChannel) GetBaud() uint32 {
	if x != nil {
		return x.Baud
	}
	return 0
}

func (x *ConfigureChannel) GetMarkFreq() uint32 {
	if x != nil {
		return x.MarkFreq
	}
	return 0
}

func (x *ConfigureChannel) GetSpaceFreq() uint32 {
	if x != nil {
		return x.SpaceFreq
	}
	return 0
}

func (x *ConfigureChannel) GetModemType() string {
	if x != nil {
		return x.ModemType
	}
	return ""
}

func (x *ConfigureChannel) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *ConfigureChannel) GetNumSlicers() uint32 {
	if x != nil {
		return x.NumSlicers
	}
	return 0
}

func (x *ConfigureChannel) GetFixBits() string {
	if x != nil {
		return x.FixBits
	}
	return ""
}

func (x *ConfigureChannel) GetNumDecoders() uint32 {
	if x != nil {
		return x.NumDecoders
	}
	return 0
}

func (x *ConfigureChannel) GetDecoderOffset() int32 {
	if x != nil {
		return x.DecoderOffset
	}
	return 0
}

func (x *ConfigureChannel) GetFx25Encode() bool {
	if x != nil {
		return x.Fx25Encode
	}
	return false
}

func (x *ConfigureChannel) GetIl2PEncode() bool {
	if x != nil {
		return x.Il2PEncode
	}
	return false
}

func (x *ConfigureChannel) GetInputDeviceId() uint32 {
	if x != nil {
		return x.InputDeviceId
	}
	return 0
}

func (x *ConfigureChannel) GetInputChannel() uint32 {
	if x != nil {
		return x.InputChannel
	}
	return 0
}

func (x *ConfigureChannel) GetOutputDeviceId() uint32 {
	if x != nil {
		return x.OutputDeviceId
	}
	return 0
}

func (x *ConfigureChannel) GetOutputChannel() uint32 {
	if x != nil {
		return x.OutputChannel
	}
	return 0
}

func (x *ConfigureChannel) GetDemodEnsemble() string {
	if x != nil {
		return x.DemodEnsemble
	}
	return ""
}

// Configure an audio source (soundcard, SDR UDP, stdin, FLAC file).
type ConfigureAudio struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DeviceId   uint32                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"` // cpal device name, "stdin", or file path
	SampleRate uint32                 `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels   uint32                 `protobuf:"varint,4,opt,name=channels,proto3" json:"channels,omitempty"`                      // 1=mono, 2=stereo
	SourceType string                 `protobuf:"bytes,5,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // "soundcard" | "stdin" | "flac" | "flac_fast" | "sdr_udp"
	// ("flac_fast" drives the FLAC decoder as
	//
	//	fast as possible with no realtime pacing,
	//	intended for benchmarking / offline runs.)
	Format        string  `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`                 // "s16le" | "f32" etc. (source-specific)
	GainDb        float32 `protobuf:"fixed32,7,opt,name=gain_db,json=gainDb,proto3" json:"gain_db,omitempty"` // software gain in dB (-60 to +12), 0 = unity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureAudio) Reset() {
	*x = ConfigureAudio{}
	mi := &file_graywolf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureAudio) ProtoMessage() {}

func (x *ConfigureAudio) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureAudio.ProtoReflect.Descriptor instead.
func (*ConfigureAudio) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigureAudio) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *ConfigureAudio) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *ConfigureAudio) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *ConfigureAudio) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *ConfigureAudio) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *ConfigureAudio) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ConfigureAudio) GetGainDb() float32 {
	if x != nil {
		return x.GainDb
	}
	return 0
}

// Configure PTT (push-to-talk) control for a channel.
type ConfigurePtt struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Channel uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Method  string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"` // "serial_rts" | "serial_dtr" | "gpio" | "cm108" | "rigctld" | "vox" | "digirig_tone" | "none"
	// device is interpreted by the selected method:
	//   - serial_rts/serial_dtr → filesystem device path, e.g. "/dev/ttyUSB0"
	//   - cm108                 → HID device path, e.g. "/dev/hidraw0"
	//   - rigctld               → "host:port", e.g. "localhost:4532" (IPv4/hostname only; no IPv6 bracketing)
	//   - gpio                  → gpiochip device path, e.g. "/dev/gpiochip0"
	//   - vox                   → ignored (radio keys on audio; a lead-in tone is prepended)
	//   - digirig_tone          → ignored (Digirig Lite keys on a tone the audio path puts on the companion channel)
	//   - none                  → ignored
	//
	// If a fourth PTT method needs to overload this field, migrate to a
	// structured `endpoint` oneof instead of piling on more string schemas.
	Device     string `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	TxdelayMs  uint32 `protobuf:"varint,4,opt,name=txdelay_ms,json=txdelayMs,proto3" json:"txdelay_ms,omitempty"`
	TxtailMs   uint32 `protobuf:"varint,5,opt,name=txtail_ms,json=txtailMs,proto3" json:"txtail_ms,omitempty"`
	SlottimeMs uint32 `protobuf:"varint,6,opt,name=slottime_ms,json=slottimeMs,proto3" json:"slottime_ms,omitempty"`
	Persist    uint32 `protobuf:"varint,7,opt,name=persist,proto3" json:"persist,omitempty"` // p-persistence 0..255
	DwaitMs    uint32 `protobuf:"varint,8,opt,name=dwait_ms,json=dwaitMs,proto3" json:"dwait_ms,omitempty"`
	Invert     bool   `protobuf:"varint,9,opt,name=invert,proto3" json:"invert,omitempty"` // reverse polarity for rigs wired backwards
	// CM108 GPIO pin number (1-indexed, default: 3). Not used for `gpio` method
	// (which uses `gpio_line` instead to avoid indexing ambiguity).
	GpioPin uint32 `protobuf:"varint,10,opt,name=gpio_pin,json=gpioPin,proto3" json:"gpio_pin,omitempty"`
	// 0-indexed GPIO line offset for the `gpio` method (gpiochip chardev v2).
	// For CM108, use `gpio_pin` (1-indexed) instead.
	GpioLine uint32 `protobuf:"varint,11,opt,name=gpio_line,json=gpioLine,proto3" json:"gpio_line,omitempty"`
	// Android USB-PTT transport selector. Carries the PttMethod enum value
	// (proto/platform.proto: 1=PTT_METHOD_CP2102N_RTS, 2=PTT_METHOD_CM108_HID,
	// 3=PTT_METHOD_AIOC_CDC_DTR, 4=PTT_METHOD_VOX,
	// 5=PTT_METHOD_DIGIRIG_TONE). Typed uint32 (not the
	// platform.proto enum) to keep this IPC contract self-contained
	// (invariant #2). Meaningful only when method=="android"; 0 otherwise.
	// Never overload gpio_pin for this.
	PttMethod     uint32 `protobuf:"varint,12,opt,name=ptt_method,json=pttMethod,proto3" json:"ptt_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurePtt) Reset() {
	*x = ConfigurePtt{}
	mi := &file_graywolf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurePtt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurePtt) ProtoMessage() {}

func (x *ConfigurePtt) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurePtt.ProtoReflect.Descriptor instead.
func (*ConfigurePtt) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigurePtt) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ConfigurePtt) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ConfigurePtt) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *ConfigurePtt) GetTxdelayMs() uint32 {
	if x != nil {
		return x.TxdelayMs
	}
	return 0
}

func (x *ConfigurePtt) GetTxtailMs() uint32 {
	if x != nil {
		return x.TxtailMs
	}
	return 0
}

func (x *ConfigurePtt) GetSlottimeMs() uint32 {
	if x != nil {
		return x.SlottimeMs
	}
	return 0
}

func (x *ConfigurePtt) GetPersist() uint32 {
	if x != nil {
		return x.Persist
	}
	return 0
}

func (x *ConfigurePtt) GetDwaitMs() uint32 {
	if x != nil {
		return x.DwaitMs
	}
	return 0
}

func (x *ConfigurePtt) GetInvert() bool {
	if x != nil {
		return x.Invert
	}
	return false
}

func (x *ConfigurePtt) GetGpioPin() uint32 {
	if x != nil {
		return x.GpioPin
	}
	return 0
}

func (x *ConfigurePtt) GetGpioLine() uint32 {
	if x != nil {
		return x.GpioLine
	}
	return 0
}

func (x *ConfigurePtt) GetPttMethod() uint32 {
	if x != nil {
		return x.PttMethod
	}
	return 0
}

// Begin audio processing on all configured devices.
type StartAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAudio) Reset() {
	*x = StartAudio{}
	mi := &file_graywolf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAudio) ProtoMessage() {}

func (x *StartAudio) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAudio.ProtoReflect.Descriptor instead.
func (*StartAudio) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{11}
}

// Stop audio processing (for device hot-swap). Safe to follow with a new
// ConfigureAudio + StartAudio sequence.
type StopAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAudio) Reset() {
	*x = StopAudio{}
	mi := &file_graywolf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAudio) ProtoMessage() {}

func (x *StopAudio) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAudio.ProtoReflect.Descriptor instead.
func (*StopAudio) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{12}
}

// Graceful shutdown: finish current TX, deassert PTT, drain queues, exit.
type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeoutMs     uint32                 `protobuf:"varint,1,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // max time to wait for drain, 0 = use default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_graywolf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{13}
}

func (x *Shutdown) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// Request enumeration of available audio devices.
type EnumerateAudioDevices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`             // echoed back in AudioDeviceList
	IncludeOutput bool                   `protobuf:"varint,2,opt,name=include_output,json=includeOutput,proto3" json:"include_output,omitempty"` // include output devices in response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateAudioDevices) Reset() {
	*x = EnumerateAudioDevices{}
	mi := &file_graywolf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateAudioDevices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateAudioDevices) ProtoMessage() {}

func (x *EnumerateAudioDevices) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateAudioDevices.ProtoReflect.Descriptor instead.
func (*EnumerateAudioDevices) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{14}
}

func (x *EnumerateAudioDevices) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *EnumerateAudioDevices) GetIncludeOutput() bool {
	if x != nil {
		return x.IncludeOutput
	}
	return false
}

// Set software gain for an audio device (live update, no restart).
type SetDeviceGain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint32                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	GainDb        float32                `protobuf:"fixed32,2,opt,name=gain_db,json=gainDb,proto3" json:"gain_db,omitempty"` // -60.0 to +12.0, 0.0 = unity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceGain) Reset() {
	*x = SetDeviceGain{}
	mi := &file_graywolf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceGain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceGain) ProtoMessage() {}

func (x *SetDeviceGain) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceGain.ProtoReflect.Descriptor instead.
func (*SetDeviceGain) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{15}
}

func (x *SetDeviceGain) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *SetDeviceGain) GetGainDb() float32 {
	if x != nil {
		return x.GainDb
	}
	return 0
}

// Per-device audio level report, emitted ~5 Hz by the modem.
type DeviceLevelUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint32                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PeakDbfs      float32                `protobuf:"fixed32,2,opt,name=peak_dbfs,json=peakDbfs,proto3" json:"peak_dbfs,omitempty"` // instantaneous peak in dBFS
	RmsDbfs       float32                `protobuf:"fixed32,3,opt,name=rms_dbfs,json=rmsDbfs,proto3" json:"rms_dbfs,omitempty"`    // RMS level in dBFS
	Clipping      bool                   `protobuf:"varint,4,opt,name=clipping,proto3" json:"clipping,omitempty"`                  // true if post-gain samples exceeded -1 dBFS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceLevelUpdate) Reset() {
	*x = DeviceLevelUpdate{}
	mi := &file_graywolf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceLevelUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceLevelUpdate) ProtoMessage() {}

func (x *DeviceLevelUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceLevelUpdate.ProtoReflect.Descriptor instead.
func (*DeviceLevelUpdate) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{16}
}

func (x *DeviceLevelUpdate) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *DeviceLevelUpdate) GetPeakDbfs() float32 {
	if x != nil {
		return x.PeakDbfs
	}
	return 0
}

func (x *DeviceLevelUpdate) GetRmsDbfs() float32 {
	if x != nil {
		return x.RmsDbfs
	}
	return 0
}

func (x *DeviceLevelUpdate) GetClipping() bool {
	if x != nil {
		return x.Clipping
	}
	return false
}

// Request a brief input level scan on all available input devices.
type ScanInputLevels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`    // echoed back in InputLevelScanResult
	DurationMs    uint32                 `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // how long to sample each device (default 500ms)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanInputLevels) Reset() {
	*x = ScanInputLevels{}
	mi := &file_graywolf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanInputLevels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanInputLevels) ProtoMessage() {}

func (x *ScanInputLevels) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanInputLevels.ProtoReflect.Descriptor instead.
func (*ScanInputLevels) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{17}
}

func (x *ScanInputLevels) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ScanInputLevels) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// Manual PTT toggle for SPA testing. The PTT driver for the channel must
// already be registered via ConfigurePtt. A 10-second Go-side watchdog
// auto-unkeys if no heartbeat arrives.
type ManualPtt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"` // logical channel
	Keyed         bool                   `protobuf:"varint,2,opt,name=keyed,proto3" json:"keyed,omitempty"`     // true = key, false = unkey
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualPtt) Reset() {
	*x = ManualPtt{}
	mi := &file_graywolf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualPtt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualPtt) ProtoMessage() {}

func (x *ManualPtt) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualPtt.ProtoReflect.Descriptor instead.
func (*ManualPtt) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{18}
}

func (x *ManualPtt) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ManualPtt) GetKeyed() bool {
	if x != nil {
		return x.Keyed
	}
	return false
}

// Result of an input level scan.
type InputLevelScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Devices       []*InputDeviceLevel    `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputLevelScanResult) Reset() {
	*x = InputLevelScanResult{}
	mi := &file_graywolf_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputLevelScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputLevelScanResult) ProtoMessage() {}

func (x *InputLevelScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputLevelScanResult.ProtoReflect.Descriptor instead.
func (*InputLevelScanResult) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{19}
}

func (x *InputLevelScanResult) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *InputLevelScanResult) GetDevices() []*InputDeviceLevel {
	if x != nil {
		return x.Devices
	}
	return nil
}

// Level reading for a single input device.
type InputDeviceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                             // cpal device name
	PeakDbfs      float32                `protobuf:"fixed32,2,opt,name=peak_dbfs,json=peakDbfs,proto3" json:"peak_dbfs,omitempty"`   // peak level during scan
	HasSignal     bool                   `protobuf:"varint,3,opt,name=has_signal,json=hasSignal,proto3" json:"has_signal,omitempty"` // true if peak > -40 dBFS
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                           // non-empty if device couldn't be opened
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputDeviceLevel) Reset() {
	*x = InputDeviceLevel{}
	mi := &file_graywolf_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputDeviceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputDeviceLevel) ProtoMessage() {}

func (x *InputDeviceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputDeviceLevel.ProtoReflect.Descriptor instead.
func (*InputDeviceLevel) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{20}
}

func (x *InputDeviceLevel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputDeviceLevel) GetPeakDbfs() float32 {
	if x != nil {
		return x.PeakDbfs
	}
	return 0
}

func (x *InputDeviceLevel) GetHasSignal() bool {
	if x != nil {
		return x.HasSignal
	}
	return false
}

func (x *InputDeviceLevel) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Go -> Rust: transmit a TX test signal on a channel. kind selects the
// generator: 0 = station callsign in CW, 1 = steady tone, 2 = alternating
// tone. Go fills the relevant parameters; the modem is a pure renderer.
type TransmitTestSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`         // echoed back in TestSignalResult
	Channel       uint32                 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`                              // selects output device + PTT driver
	Kind          uint32                 `protobuf:"varint,3,opt,name=kind,proto3" json:"kind,omitempty"`                                    // 0=CW callsign, 1=steady tone, 2=alternating
	Callsign      string                 `protobuf:"bytes,4,opt,name=callsign,proto3" json:"callsign,omitempty"`                             // kind 0; already resolved + uppercased by Go
	CwWpm         uint32                 `protobuf:"varint,5,opt,name=cw_wpm,json=cwWpm,proto3" json:"cw_wpm,omitempty"`                     // kind 0
	FreqAHz       uint32                 `protobuf:"varint,6,opt,name=freq_a_hz,json=freqAHz,proto3" json:"freq_a_hz,omitempty"`             // CW sidetone (0) / tone (1) / tone A (2)
	FreqBHz       uint32                 `protobuf:"varint,7,opt,name=freq_b_hz,json=freqBHz,proto3" json:"freq_b_hz,omitempty"`             // tone B (kind 2)
	DurationMs    uint32                 `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`      // kinds 1, 2
	AltPeriodMs   uint32                 `protobuf:"varint,9,opt,name=alt_period_ms,json=altPeriodMs,proto3" json:"alt_period_ms,omitempty"` // kind 2: ms per tone before switching
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransmitTestSignal) Reset() {
	*x = TransmitTestSignal{}
	mi := &file_graywolf_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransmitTestSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransmitTestSignal) ProtoMessage() {}

func (x *TransmitTestSignal) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransmitTestSignal.ProtoReflect.Descriptor instead.
func (*TransmitTestSignal) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{21}
}

func (x *TransmitTestSignal) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TransmitTestSignal) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *TransmitTestSignal) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *TransmitTestSignal) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *TransmitTestSignal) GetCwWpm() uint32 {
	if x != nil {
		return x.CwWpm
	}
	return 0
}

func (x *TransmitTestSignal) GetFreqAHz() uint32 {
	if x != nil {
		return x.FreqAHz
	}
	return 0
}

func (x *TransmitTestSignal) GetFreqBHz() uint32 {
	if x != nil {
		return x.FreqBHz
	}
	return 0
}

func (x *TransmitTestSignal) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TransmitTestSignal) GetAltPeriodMs() uint32 {
	if x != nil {
		return x.AltPeriodMs
	}
	return 0
}

// Result of a TX test-signal submission to the TX worker.
type TestSignalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // empty on success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestSignalResult) Reset() {
	*x = TestSignalResult{}
	mi := &file_graywolf_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestSignalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSignalResult) ProtoMessage() {}

func (x *TestSignalResult) ProtoReflect() protoreflect.Message {
	mi := &file_graywolf_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSignalResult.ProtoReflect.Descriptor instead.
func (*TestSignalResult) Descriptor() ([]byte, []int) {
	return file_graywolf_proto_rawDescGZIP(), []int{22}
}

func (x *TestSignalResult) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TestSignalResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestSignalResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_graywolf_proto protoreflect.FileDescriptor

const file_graywolf_proto_rawDesc = "" +
	"\n" +
	"\x0egraywolf.proto\x12\bgraywolf\"\xe5\n" +
	"\n" +
	"\n" +
	"IpcMessage\x12@\n" +
	"\x0ereceived_frame\x18\x01 \x01(\v2\x17.graywolf.ReceivedFrameH\x00R\rreceivedFrame\x124\n" +
	"\n" +
	"dcd_change\x18\x02 \x01(\v2\x13.graywolf.DcdChangeH\x00R\tdcdChange\x12=\n" +
	"\rstatus_update\x18\x03 \x01(\v2\x16.graywolf.StatusUpdateH\x00R\fstatusUpdate\x127\n" +
	"\vmodem_ready\x18\x04 \x01(\v2\x14.graywolf.ModemReadyH\x00R\n" +
	"modemReady\x12G\n" +
	"\x11audio_device_list\x18\x05 \x01(\v2\x19.graywolf.AudioDeviceListH\x00R\x0faudioDeviceList\x12M\n" +
	"\x13device_level_update\x18\a \x01(\v2\x1b.graywolf.DeviceLevelUpdateH\x00R\x11deviceLevelUpdate\x12W\n" +
	"\x17input_level_scan_result\x18\b \x01(\v2\x1e.graywolf.InputLevelScanResultH\x00R\x14inputLevelScanResult\x12J\n" +
	"\x12test_signal_result\x18\t \x01(\v2\x1a.graywolf.TestSignalResultH\x00R\x10testSignalResult\x12@\n" +
	"\x0etransmit_frame\x18\n" +
	" \x01(\v2\x17.graywolf.TransmitFrameH\x00R\rtransmitFrame\x12I\n" +
	"\x11configure_channel\x18\v \x01(\v2\x1a.graywolf.ConfigureChannelH\x00R\x10configureChannel\x12C\n" +
	"\x0fconfigure_audio\x18\f \x01(\v2\x18.graywolf.ConfigureAudioH\x00R\x0econfigureAudio\x12=\n" +
	"\rconfigure_ptt\x18\r \x01(\v2\x16.graywolf.ConfigurePttH\x00R\fconfigurePtt\x127\n" +
	"\vstart_audio\x18\x0e \x01(\v2\x14.graywolf.StartAudioH\x00R\n" +
	"startAudio\x124\n" +
	"\n" +
	"stop_audio\x18\x0f \x01(\v2\x13.graywolf.StopAudioH\x00R\tstopAudio\x120\n" +
	"\bshutdown\x18\x10 \x01(\v2\x12.graywolf.ShutdownH\x00R\bshutdown\x12Y\n" +
	"\x17enumerate_audio_devices\x18\x11 \x01(\v2\x1f.graywolf.EnumerateAudioDevicesH\x00R\x15enumerateAudioDevices\x12A\n" +
	"\x0fset_device_gain\x18\x13 \x01(\v2\x17.graywolf.SetDeviceGainH\x00R\rsetDeviceGain\x12G\n" +
	"\x11scan_input_levels\x18\x14 \x01(\v2\x19.graywolf.ScanInputLevelsH\x00R\x0fscanInputLevels\x124\n" +
	"\n" +
	"manual_ptt\x18\x15 \x01(\v2\x13.graywolf.ManualPttH\x00R\tmanualPtt\x12P\n" +
	"\x14transmit_test_signal\x18\x16 \x01(\v2\x1c.graywolf.TransmitTestSignalH\x00R\x12transmitTestSignalB\t\n" +
	"\apayload\"\xb7\x02\n" +
	"\rReceivedFrame\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x18\n" +
	"\asubchan\x18\x02 \x01(\rR\asubchan\x12\x14\n" +
	"\x05slice\x18\x03 \x01(\rR\x05slice\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x18\n" +
	"\aquality\x18\x05 \x01(\x05R\aquality\x12(\n" +
	"\x10audio_level_mark\x18\x06 \x01(\x02R\x0eaudioLevelMark\x12*\n" +
	"\x11audio_level_space\x18\a \x01(\x02R\x0faudioLevelSpace\x12\x1f\n" +
	"\vspeed_error\x18\b \x01(\x02R\n" +
	"speedError\x12\x14\n" +
	"\x05retry\x18\t \x01(\tR\x05retry\x12!\n" +
	"\ftimestamp_ns\x18\n" +
	" \x01(\x04R\vtimestampNs\"\x94\x01\n" +
	"\tDcdChange\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x18\n" +
	"\asubchan\x18\x02 \x01(\rR\asubchan\x12\x14\n" +
	"\x05slice\x18\x03 \x01(\rR\x05slice\x12\x1a\n" +
	"\bdetected\x18\x04 \x01(\bR\bdetected\x12!\n" +
	"\ftimestamp_ns\x18\x05 \x01(\x04R\vtimestampNs\"\x96\x03\n" +
	"\fStatusUpdate\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x1b\n" +
	"\trx_frames\x18\x02 \x01(\x04R\brxFrames\x12\x1c\n" +
	"\n" +
	"rx_bad_fcs\x18\x03 \x01(\x04R\brxBadFcs\x12\x1b\n" +
	"\ttx_frames\x18\x04 \x01(\x04R\btxFrames\x12'\n" +
	"\x0fdcd_transitions\x18\x05 \x01(\x04R\x0edcdTransitions\x12(\n" +
	"\x10audio_level_mark\x18\x06 \x01(\x02R\x0eaudioLevelMark\x12*\n" +
	"\x11audio_level_space\x18\a \x01(\x02R\x0faudioLevelSpace\x12(\n" +
	"\x10audio_level_peak\x18\b \x01(\x02R\x0eaudioLevelPeak\x12\x1b\n" +
	"\tdcd_state\x18\t \x01(\bR\bdcdState\x12+\n" +
	"\x11shutdown_complete\x18\n" +
	" \x01(\bR\x10shutdownComplete\x12!\n" +
	"\ftimestamp_ns\x18\v \x01(\x04R\vtimestampNs\"8\n" +
	"\n" +
	"ModemReady\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x04R\x03pid\"e\n" +
	"\x0fAudioDeviceList\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x123\n" +
	"\adevices\x18\x02 \x03(\v2\x19.graywolf.AudioDeviceInfoR\adevices\"\xf7\x02\n" +
	"\x0fAudioDeviceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tstable_id\x18\x02 \x01(\tR\bstableId\x12-\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x19.graywolf.AudioDeviceKindR\x04kind\x12!\n" +
	"\fsample_rates\x18\x04 \x03(\rR\vsampleRates\x12%\n" +
	"\x0echannel_counts\x18\x05 \x03(\rR\rchannelCounts\x12\x19\n" +
	"\bhost_api\x18\x06 \x01(\tR\ahostApi\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12 \n" +
	"\vrecommended\x18\t \x01(\bR\vrecommended\x12<\n" +
	"\x1aaudio_enhancements_enabled\x18\n" +
	" \x01(\bR\x18audioEnhancementsEnabled\"\xd2\x01\n" +
	"\rTransmitFrame\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12.\n" +
	"\x13txdelay_override_ms\x18\x03 \x01(\rR\x11txdelayOverrideMs\x12,\n" +
	"\x12txtail_override_ms\x18\x04 \x01(\rR\x10txtailOverrideMs\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\rR\bpriority\x12\x19\n" +
	"\bframe_id\x18\x06 \x01(\x04R\aframeId\"\x84\x05\n" +
	"\x10ConfigureChannel\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\rR\bdeviceId\x12#\n" +
	"\raudio_channel\x18\x03 \x01(\rR\faudioChannel\x12\x12\n" +
	"\x04baud\x18\x04 \x01(\rR\x04baud\x12\x1b\n" +
	"\tmark_freq\x18\x05 \x01(\rR\bmarkFreq\x12\x1d\n" +
	"\n" +
	"space_freq\x18\x06 \x01(\rR\tspaceFreq\x12\x1d\n" +
	"\n" +
	"modem_type\x18\a \x01(\tR\tmodemType\x12\x18\n" +
	"\aprofile\x18\b \x01(\tR\aprofile\x12\x1f\n" +
	"\vnum_slicers\x18\t \x01(\rR\n" +
	"numSlicers\x12\x19\n" +
	"\bfix_bits\x18\n" +
	" \x01(\tR\afixBits\x12!\n" +
	"\fnum_decoders\x18\v \x01(\rR\vnumDecoders\x12%\n" +
	"\x0edecoder_offset\x18\f \x01(\x05R\rdecoderOffset\x12\x1f\n" +
	"\vfx25_encode\x18\r \x01(\bR\n" +
	"fx25Encode\x12\x1f\n" +
	"\vil2p_encode\x18\x0e \x01(\bR\n" +
	"il2pEncode\x12&\n" +
	"\x0finput_device_id\x18\x0f \x01(\rR\rinputDeviceId\x12#\n" +
	"\rinput_channel\x18\x10 \x01(\rR\finputChannel\x12(\n" +
	"\x10output_device_id\x18\x11 \x01(\rR\x0eoutputDeviceId\x12%\n" +
	"\x0eoutput_channel\x18\x12 \x01(\rR\routputChannel\x12%\n" +
	"\x0edemod_ensemble\x18\x13 \x01(\tR\rdemodEnsemble\"\xdd\x01\n" +
	"\x0eConfigureAudio\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\rR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\rR\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x04 \x01(\rR\bchannels\x12\x1f\n" +
	"\vsource_type\x18\x05 \x01(\tR\n" +
	"sourceType\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\x12\x17\n" +
	"\again_db\x18\a \x01(\x02R\x06gainDb\"\xd9\x02\n" +
	"\fConfigurePtt\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12\x1d\n" +
	"\n" +
	"txdelay_ms\x18\x04 \x01(\rR\ttxdelayMs\x12\x1b\n" +
	"\ttxtail_ms\x18\x05 \x01(\rR\btxtailMs\x12\x1f\n" +
	"\vslottime_ms\x18\x06 \x01(\rR\n" +
	"slottimeMs\x12\x18\n" +
	"\apersist\x18\a \x01(\rR\apersist\x12\x19\n" +
	"\bdwait_ms\x18\b \x01(\rR\adwaitMs\x12\x16\n" +
	"\x06invert\x18\t \x01(\bR\x06invert\x12\x19\n" +
	"\bgpio_pin\x18\n" +
	" \x01(\rR\agpioPin\x12\x1b\n" +
	"\tgpio_line\x18\v \x01(\rR\bgpioLine\x12\x1d\n" +
	"\n" +
	"ptt_method\x18\f \x01(\rR\tpttMethod\"\f\n" +
	"\n" +
	"StartAudio\"\v\n" +
	"\tStopAudio\")\n" +
	"\bShutdown\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x01 \x01(\rR\ttimeoutMs\"]\n" +
	"\x15EnumerateAudioDevices\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12%\n" +
	"\x0einclude_output\x18\x02 \x01(\bR\rincludeOutput\"E\n" +
	"\rSetDeviceGain\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\rR\bdeviceId\x12\x17\n" +
	"\again_db\x18\x02 \x01(\x02R\x06gainDb\"\x84\x01\n" +
	"\x11DeviceLevelUpdate\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\rR\bdeviceId\x12\x1b\n" +
	"\tpeak_dbfs\x18\x02 \x01(\x02R\bpeakDbfs\x12\x19\n" +
	"\brms_dbfs\x18\x03 \x01(\x02R\armsDbfs\x12\x1a\n" +
	"\bclipping\x18\x04 \x01(\bR\bclipping\"Q\n" +
	"\x0fScanInputLevels\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\rR\n" +
	"durationMs\";\n" +
	"\tManualPtt\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x14\n" +
	"\x05keyed\x18\x02 \x01(\bR\x05keyed\"k\n" +
	"\x14InputLevelScanResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x124\n" +
	"\adevices\x18\x02 \x03(\v2\x1a.graywolf.InputDeviceLevelR\adevices\"x\n" +
	"\x10InputDeviceLevel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tpeak_dbfs\x18\x02 \x01(\x02R\bpeakDbfs\x12\x1d\n" +
	"\n" +
	"has_signal\x18\x03 \x01(\bR\thasSignal\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x91\x02\n" +
	"\x12TransmitTestSignal\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\rR\achannel\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\rR\x04kind\x12\x1a\n" +
	"\bcallsign\x18\x04 \x01(\tR\bcallsign\x12\x15\n" +
	"\x06cw_wpm\x18\x05 \x01(\rR\x05cwWpm\x12\x1a\n" +
	"\tfreq_a_hz\x18\x06 \x01(\rR\afreqAHz\x12\x1a\n" +
	"\tfreq_b_hz\x18\a \x01(\rR\afreqBHz\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\rR\n" +
	"durationMs\x12\"\n" +
	"\ralt_period_ms\x18\t \x01(\rR\valtPeriodMs\"a\n" +
	"\x10TestSignalResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*o\n" +
	"\x0fAudioDeviceKind\x12!\n" +
	"\x1dAUDIO_DEVICE_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17AUDIO_DEVICE_KIND_INPUT\x10\x01\x12\x1c\n" +
	"\x18AUDIO_DEVICE_KIND_OUTPUT\x10\x02B-Z+github.com/chrissnell/graywolf/pkg/ipcprotob\x06proto3"

var (
	file_graywolf_proto_rawDescOnce sync.Once
	file_graywolf_proto_rawDescData []byte
)

func file_graywolf_proto_rawDescGZIP() []byte {
	file_graywolf_proto_rawDescOnce.Do(func() {
		file_graywolf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graywolf_proto_rawDesc), len(file_graywolf_proto_rawDesc)))
	})
	return file_graywolf_proto_rawDescData
}

var file_graywolf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_graywolf_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_graywolf_proto_goTypes = []any{
	(AudioDeviceKind)(0),          // 0: graywolf.AudioDeviceKind
	(*IpcMessage)(nil),            // 1: graywolf.IpcMessage
	(*ReceivedFrame)(nil),         // 2: graywolf.ReceivedFrame
	(*DcdChange)(nil),             // 3: graywolf.DcdChange
	(*StatusUpdate)(nil),          // 4: graywolf.StatusUpdate
	(*ModemReady)(nil),            // 5: graywolf.ModemReady
	(*AudioDeviceList)(nil),       // 6: graywolf.AudioDeviceList
	(*AudioDeviceInfo)(nil),       // 7: graywolf.AudioDeviceInfo
	(*TransmitFrame)(nil),         // 8: graywolf.TransmitFrame
	(*ConfigureChannel)(nil),      // 9: graywolf.ConfigureChannel
	(*ConfigureAudio)(nil),        // 10: graywolf.ConfigureAudio
	(*ConfigurePtt)(nil),          // 11: graywolf.ConfigurePtt
	(*StartAudio)(nil),            // 12: graywolf.StartAudio
	(*StopAudio)(nil),             // 13: graywolf.StopAudio
	(*Shutdown)(nil),              // 14: graywolf.Shutdown
	(*EnumerateAudioDevices)(nil), // 15: graywolf.EnumerateAudioDevices
	(*SetDeviceGain)(nil),         // 16: graywolf.SetDeviceGain
	(*DeviceLevelUpdate)(nil),     // 17: graywolf.DeviceLevelUpdate
	(*ScanInputLevels)(nil),       // 18: graywolf.ScanInputLevels
	(*ManualPtt)(nil),             // 19: graywolf.ManualPtt
	(*InputLevelScanResult)(nil),  // 20: graywolf.InputLevelScanResult
	(*InputDeviceLevel)(nil),      // 21: graywolf.InputDeviceLevel
	(*TransmitTestSignal)(nil),    // 22: graywolf.TransmitTestSignal
	(*TestSignalResult)(nil),      // 23: graywolf.TestSignalResult
}
var file_graywolf_proto_depIdxs = []int32{
	2,  // 0: graywolf.IpcMessage.received_frame:type_name -> graywolf.ReceivedFrame
	3,  // 1: graywolf.IpcMessage.dcd_change:type_name -> graywolf.DcdChange
	4,  // 2: graywolf.IpcMessage.status_update:type_name -> graywolf.StatusUpdate
	5,  // 3: graywolf.IpcMessage.modem_ready:type_name -> graywolf.ModemReady
	6,  // 4: graywolf.IpcMessage.audio_device_list:type_name -> graywolf.AudioDeviceList
	17, // 5: graywolf.IpcMessage.device_level_update:type_name -> graywolf.DeviceLevelUpdate
	20, // 6: graywolf.IpcMessage.input_level_scan_result:type_name -> graywolf.InputLevelScanResult
	23, // 7: graywolf.IpcMessage.test_signal_result:type_name -> graywolf.TestSignalResult
	8,  // 8: graywolf.IpcMessage.transmit_frame:type_name -> graywolf.TransmitFrame
	9,  // 9: graywolf.IpcMessage.configure_channel:type_name -> graywolf.ConfigureChannel
	10, // 10: graywolf.IpcMessage.configure_audio:type_name -> graywolf.ConfigureAudio
	11, // 11: graywolf.IpcMessage.configure_ptt:type_name -> graywolf.ConfigurePtt
	12, // 12: graywolf.IpcMessage.start_audio:type_name -> graywolf.StartAudio
	13, // 13: graywolf.IpcMessage.stop_audio:type_name -> graywolf.StopAudio
	14, // 14: graywolf.IpcMessage.shutdown:type_name -> graywolf.Shutdown
	15, // 15: graywolf.IpcMessage.enumerate_audio_devices:type_name -> graywolf.EnumerateAudioDevices
	16, // 16: graywolf.IpcMessage.set_device_gain:type_name -> graywolf.SetDeviceGain
	18, // 17: graywolf.IpcMessage.scan_input_levels:type_name -> graywolf.ScanInputLevels
	19, // 18: graywolf.IpcMessage.manual_ptt:type_name -> graywolf.ManualPtt
	22, // 19: graywolf.IpcMessage.transmit_test_signal:type_name -> graywolf.TransmitTestSignal
	7,  // 20: graywolf.AudioDeviceList.devices:type_name -> graywolf.AudioDeviceInfo
	0,  // 21: graywolf.AudioDeviceInfo.kind:type_name -> graywolf.AudioDeviceKind
	21, // 22: graywolf.InputLevelScanResult.devices:type_name -> graywolf.InputDeviceLevel
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_graywolf_proto_init() }
func file_graywolf_proto_init() {
	if File_graywolf_proto != nil {
		return
	}
	file_graywolf_proto_msgTypes[0].OneofWrappers = []any{
		(*IpcMessage_ReceivedFrame)(nil),
		(*IpcMessage_DcdChange)(nil),
		(*IpcMessage_StatusUpdate)(nil),
		(*IpcMessage_ModemReady)(nil),
		(*IpcMessage_AudioDeviceList)(nil),
		(*IpcMessage_DeviceLevelUpdate)(nil),
		(*IpcMessage_InputLevelScanResult)(nil),
		(*IpcMessage_TestSignalResult)(nil),
		(*IpcMessage_TransmitFrame)(nil),
		(*IpcMessage_ConfigureChannel)(nil),
		(*IpcMessage_ConfigureAudio)(nil),
		(*IpcMessage_ConfigurePtt)(nil),
		(*IpcMessage_StartAudio)(nil),
		(*IpcMessage_StopAudio)(nil),
		(*IpcMessage_Shutdown)(nil),
		(*IpcMessage_EnumerateAudioDevices)(nil),
		(*IpcMessage_SetDeviceGain)(nil),
		(*IpcMessage_ScanInputLevels)(nil),
		(*IpcMessage_ManualPtt)(nil),
		(*IpcMessage_TransmitTestSignal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graywolf_proto_rawDesc), len(file_graywolf_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graywolf_proto_goTypes,
		DependencyIndexes: file_graywolf_proto_depIdxs,
		EnumInfos:         file_graywolf_proto_enumTypes,
		MessageInfos:      file_graywolf_proto_msgTypes,
	}.Build()
	File_graywolf_proto = out.File
	file_graywolf_proto_goTypes = nil
	file_graywolf_proto_depIdxs = nil
}
