// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: platform.proto

package platformproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GpsSource int32

const (
	GpsSource_GPS_SOURCE_UNKNOWN         GpsSource = 0
	GpsSource_GPS_SOURCE_ANDROID_FUSED   GpsSource = 1
	GpsSource_GPS_SOURCE_ANDROID_GPS     GpsSource = 2
	GpsSource_GPS_SOURCE_ANDROID_NETWORK GpsSource = 3
)

// Enum value maps for GpsSource.
var (
	GpsSource_name = map[int32]string{
		0: "GPS_SOURCE_UNKNOWN",
		1: "GPS_SOURCE_ANDROID_FUSED",
		2: "GPS_SOURCE_ANDROID_GPS",
		3: "GPS_SOURCE_ANDROID_NETWORK",
	}
	GpsSource_value = map[string]int32{
		"GPS_SOURCE_UNKNOWN":         0,
		"GPS_SOURCE_ANDROID_FUSED":   1,
		"GPS_SOURCE_ANDROID_GPS":     2,
		"GPS_SOURCE_ANDROID_NETWORK": 3,
	}
)

func (x GpsSource) Enum() *GpsSource {
	p := new(GpsSource)
	*p = x
	return p
}

func (x GpsSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GpsSource) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_proto_enumTypes[0].Descriptor()
}

func (GpsSource) Type() protoreflect.EnumType {
	return &file_platform_proto_enumTypes[0]
}

func (x GpsSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GpsSource.Descriptor instead.
func (GpsSource) EnumDescriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{0}
}

type UsbClass int32

const (
	UsbClass_USB_CLASS_UNKNOWN UsbClass = 0
	UsbClass_USB_CLASS_AUDIO   UsbClass = 1
	UsbClass_USB_CLASS_HID     UsbClass = 2
	UsbClass_USB_CLASS_CDC_ACM UsbClass = 3
	UsbClass_USB_CLASS_VENDOR  UsbClass = 4
)

// Enum value maps for UsbClass.
var (
	UsbClass_name = map[int32]string{
		0: "USB_CLASS_UNKNOWN",
		1: "USB_CLASS_AUDIO",
		2: "USB_CLASS_HID",
		3: "USB_CLASS_CDC_ACM",
		4: "USB_CLASS_VENDOR",
	}
	UsbClass_value = map[string]int32{
		"USB_CLASS_UNKNOWN": 0,
		"USB_CLASS_AUDIO":   1,
		"USB_CLASS_HID":     2,
		"USB_CLASS_CDC_ACM": 3,
		"USB_CLASS_VENDOR":  4,
	}
)

func (x UsbClass) Enum() *UsbClass {
	p := new(UsbClass)
	*p = x
	return p
}

func (x UsbClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UsbClass) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_proto_enumTypes[1].Descriptor()
}

func (UsbClass) Type() protoreflect.EnumType {
	return &file_platform_proto_enumTypes[1]
}

func (x UsbClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UsbClass.Descriptor instead.
func (UsbClass) EnumDescriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{1}
}

type PttMethod int32

const (
	PttMethod_PTT_METHOD_UNKNOWN      PttMethod = 0
	PttMethod_PTT_METHOD_CP2102N_RTS  PttMethod = 1
	PttMethod_PTT_METHOD_CM108_HID    PttMethod = 2
	PttMethod_PTT_METHOD_AIOC_CDC_DTR PttMethod = 3
	PttMethod_PTT_METHOD_VOX          PttMethod = 4
	PttMethod_PTT_METHOD_DIGIRIG_TONE PttMethod = 5
)

// Enum value maps for PttMethod.
var (
	PttMethod_name = map[int32]string{
		0: "PTT_METHOD_UNKNOWN",
		1: "PTT_METHOD_CP2102N_RTS",
		2: "PTT_METHOD_CM108_HID",
		3: "PTT_METHOD_AIOC_CDC_DTR",
		4: "PTT_METHOD_VOX",
		5: "PTT_METHOD_DIGIRIG_TONE",
	}
	PttMethod_value = map[string]int32{
		"PTT_METHOD_UNKNOWN":      0,
		"PTT_METHOD_CP2102N_RTS":  1,
		"PTT_METHOD_CM108_HID":    2,
		"PTT_METHOD_AIOC_CDC_DTR": 3,
		"PTT_METHOD_VOX":          4,
		"PTT_METHOD_DIGIRIG_TONE": 5,
	}
)

func (x PttMethod) Enum() *PttMethod {
	p := new(PttMethod)
	*p = x
	return p
}

func (x PttMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PttMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_proto_enumTypes[2].Descriptor()
}

func (PttMethod) Type() protoreflect.EnumType {
	return &file_platform_proto_enumTypes[2]
}

func (x PttMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PttMethod.Descriptor instead.
func (PttMethod) EnumDescriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{2}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_UNKNOWN           ErrorCode = 0
	ErrorCode_ERROR_NOT_IMPLEMENTED   ErrorCode = 1
	ErrorCode_ERROR_SCHEMA_MISMATCH   ErrorCode = 2
	ErrorCode_ERROR_INVALID_ARGUMENT  ErrorCode = 3
	ErrorCode_ERROR_PERMISSION_DENIED ErrorCode = 4
	ErrorCode_ERROR_NOT_FOUND         ErrorCode = 5
	ErrorCode_ERROR_INTERNAL          ErrorCode = 6
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_UNKNOWN",
		1: "ERROR_NOT_IMPLEMENTED",
		2: "ERROR_SCHEMA_MISMATCH",
		3: "ERROR_INVALID_ARGUMENT",
		4: "ERROR_PERMISSION_DENIED",
		5: "ERROR_NOT_FOUND",
		6: "ERROR_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_UNKNOWN":           0,
		"ERROR_NOT_IMPLEMENTED":   1,
		"ERROR_SCHEMA_MISMATCH":   2,
		"ERROR_INVALID_ARGUMENT":  3,
		"ERROR_PERMISSION_DENIED": 4,
		"ERROR_NOT_FOUND":         5,
		"ERROR_INTERNAL":          6,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_proto_enumTypes[3].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_platform_proto_enumTypes[3]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{3}
}

// SerialKind classifies a transport-agnostic byte stream the platform
// service is asked to open.
type SerialKind int32

const (
	SerialKind_SERIAL_KIND_UNSPECIFIED SerialKind = 0
	SerialKind_SERIAL_KIND_BLUETOOTH   SerialKind = 1
	SerialKind_SERIAL_KIND_USB         SerialKind = 2
	SerialKind_SERIAL_KIND_BLE         SerialKind = 3
)

// Enum value maps for SerialKind.
var (
	SerialKind_name = map[int32]string{
		0: "SERIAL_KIND_UNSPECIFIED",
		1: "SERIAL_KIND_BLUETOOTH",
		2: "SERIAL_KIND_USB",
		3: "SERIAL_KIND_BLE",
	}
	SerialKind_value = map[string]int32{
		"SERIAL_KIND_UNSPECIFIED": 0,
		"SERIAL_KIND_BLUETOOTH":   1,
		"SERIAL_KIND_USB":         2,
		"SERIAL_KIND_BLE":         3,
	}
)

func (x SerialKind) Enum() *SerialKind {
	p := new(SerialKind)
	*p = x
	return p
}

func (x SerialKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SerialKind) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_proto_enumTypes[4].Descriptor()
}

func (SerialKind) Type() protoreflect.EnumType {
	return &file_platform_proto_enumTypes[4]
}

func (x SerialKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SerialKind.Descriptor instead.
func (SerialKind) EnumDescriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{4}
}

// Top-level envelope. Every message on the wire is a PlatformMessage.
// Wire framing (matches pkg/modembridge/framing.go):
//
//	[4 BE bytes length][serialized PlatformMessage bytes]
type PlatformMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*PlatformMessage_Hello
	//	*PlatformMessage_GpsFix
	//	*PlatformMessage_BatteryState
	//	*PlatformMessage_UsbAttach
	//	*PlatformMessage_UsbDetach
	//	*PlatformMessage_UsbListReq
	//	*PlatformMessage_UsbListResp
	//	*PlatformMessage_UsbSelectReq
	//	*PlatformMessage_UsbSelectResp
	//	*PlatformMessage_PttKeyReq
	//	*PlatformMessage_PttUnkeyReq
	//	*PlatformMessage_PttAck
	//	*PlatformMessage_AudioListReq
	//	*PlatformMessage_AudioListResp
	//	*PlatformMessage_AudioRouteChanged
	//	*PlatformMessage_Error
	//	*PlatformMessage_GnssStatus
	//	*PlatformMessage_SerialOpen
	//	*PlatformMessage_SerialOpenAck
	//	*PlatformMessage_SerialData
	//	*PlatformMessage_SerialClose
	//	*PlatformMessage_SerialError
	//	*PlatformMessage_BondedBtDevicesRequest
	//	*PlatformMessage_BondedBtDevicesResponse
	//	*PlatformMessage_AvailableUsbSerialDevicesRequest
	//	*PlatformMessage_AvailableUsbSerialDevicesResponse
	//	*PlatformMessage_BleScanRequest
	//	*PlatformMessage_BleScanResult
	//	*PlatformMessage_BleScanError
	//	*PlatformMessage_BleScanStop
	Body          isPlatformMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformMessage) Reset() {
	*x = PlatformMessage{}
	mi := &file_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformMessage) ProtoMessage() {}

func (x *PlatformMessage) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformMessage.ProtoReflect.Descriptor instead.
func (*PlatformMessage) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{0}
}

func (x *PlatformMessage) GetBody() isPlatformMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PlatformMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *PlatformMessage) GetGpsFix() *GpsFix {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_GpsFix); ok {
			return x.GpsFix
		}
	}
	return nil
}

func (x *PlatformMessage) GetBatteryState() *BatteryState {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_BatteryState); ok {
			return x.BatteryState
		}
	}
	return nil
}

func (x *PlatformMessage) GetUsbAttach() *UsbAttach {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_UsbAttach); ok {
			return x.UsbAttach
		}
	}
	return nil
}

func (x *PlatformMessage) GetUsbDetach() *UsbDetach {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_UsbDetach); ok {
			return x.UsbDetach
		}
	}
	return nil
}

func (x *PlatformMessage) GetUsbListReq() *UsbDeviceListRequest {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_UsbListReq); ok {
			return x.UsbListReq
		}
	}
	return nil
}

func (x *PlatformMessage) GetUsbListResp() *UsbDeviceListResponse {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_UsbListResp); ok {
			return x.UsbListResp
		}
	}
	return nil
}

func (x *PlatformMessage) GetUsbSelectReq() *UsbSelectRequest {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_UsbSelectReq); ok {
			return x.UsbSelectReq
		}
	}
	return nil
}

func (x *PlatformMessage) GetUsbSelectResp() *UsbSelectResponse {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_UsbSelectResp); ok {
			return x.UsbSelectResp
		}
	}
	return nil
}

func (x *PlatformMessage) GetPttKeyReq() *PttKeyRequest {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_PttKeyReq); ok {
			return x.PttKeyReq
		}
	}
	return nil
}

func (x *PlatformMessage) GetPttUnkeyReq() *PttUnkeyRequest {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_PttUnkeyReq); ok {
			return x.PttUnkeyReq
		}
	}
	return nil
}

func (x *PlatformMessage) GetPttAck() *PttAck {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_PttAck); ok {
			return x.PttAck
		}
	}
	return nil
}

func (x *PlatformMessage) GetAudioListReq() *AudioDeviceListRequest {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_AudioListReq); ok {
			return x.AudioListReq
		}
	}
	return nil
}

func (x *PlatformMessage) GetAudioListResp() *AudioDeviceListResponse {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_AudioListResp); ok {
			return x.AudioListResp
		}
	}
	return nil
}

func (x *PlatformMessage) GetAudioRouteChanged() *AudioRouteChanged {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_AudioRouteChanged); ok {
			return x.AudioRouteChanged
		}
	}
	return nil
}

func (x *PlatformMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *PlatformMessage) GetGnssStatus() *GnssStatusUpdate {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_GnssStatus); ok {
			return x.GnssStatus
		}
	}
	return nil
}

func (x *PlatformMessage) GetSerialOpen() *SerialOpen {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_SerialOpen); ok {
			return x.SerialOpen
		}
	}
	return nil
}

func (x *PlatformMessage) GetSerialOpenAck() *SerialOpenAck {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_SerialOpenAck); ok {
			return x.SerialOpenAck
		}
	}
	return nil
}

func (x *PlatformMessage) GetSerialData() *SerialData {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_SerialData); ok {
			return x.SerialData
		}
	}
	return nil
}

func (x *PlatformMessage) GetSerialClose() *SerialClose {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_SerialClose); ok {
			return x.SerialClose
		}
	}
	return nil
}

func (x *PlatformMessage) GetSerialError() *SerialError {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_SerialError); ok {
			return x.SerialError
		}
	}
	return nil
}

func (x *PlatformMessage) GetBondedBtDevicesRequest() *BondedBtDevicesRequest {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_BondedBtDevicesRequest); ok {
			return x.BondedBtDevicesRequest
		}
	}
	return nil
}

func (x *PlatformMessage) GetBondedBtDevicesResponse() *BondedBtDevicesResponse {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_BondedBtDevicesResponse); ok {
			return x.BondedBtDevicesResponse
		}
	}
	return nil
}

func (x *PlatformMessage) GetAvailableUsbSerialDevicesRequest() *AvailableUsbSerialDevicesRequest {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_AvailableUsbSerialDevicesRequest); ok {
			return x.AvailableUsbSerialDevicesRequest
		}
	}
	return nil
}

func (x *PlatformMessage) GetAvailableUsbSerialDevicesResponse() *AvailableUsbSerialDevicesResponse {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_AvailableUsbSerialDevicesResponse); ok {
			return x.AvailableUsbSerialDevicesResponse
		}
	}
	return nil
}

func (x *PlatformMessage) GetBleScanRequest() *BleScanRequest {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_BleScanRequest); ok {
			return x.BleScanRequest
		}
	}
	return nil
}

func (x *PlatformMessage) GetBleScanResult() *BleScanResult {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_BleScanResult); ok {
			return x.BleScanResult
		}
	}
	return nil
}

func (x *PlatformMessage) GetBleScanError() *BleScanError {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_BleScanError); ok {
			return x.BleScanError
		}
	}
	return nil
}

func (x *PlatformMessage) GetBleScanStop() *BleScanStop {
	if x != nil {
		if x, ok := x.Body.(*PlatformMessage_BleScanStop); ok {
			return x.BleScanStop
		}
	}
	return nil
}

type isPlatformMessage_Body interface {
	isPlatformMessage_Body()
}

type PlatformMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type PlatformMessage_GpsFix struct {
	GpsFix *GpsFix `protobuf:"bytes,2,opt,name=gps_fix,json=gpsFix,proto3,oneof"`
}

type PlatformMessage_BatteryState struct {
	BatteryState *BatteryState `protobuf:"bytes,3,opt,name=battery_state,json=batteryState,proto3,oneof"`
}

type PlatformMessage_UsbAttach struct {
	UsbAttach *UsbAttach `protobuf:"bytes,4,opt,name=usb_attach,json=usbAttach,proto3,oneof"`
}

type PlatformMessage_UsbDetach struct {
	UsbDetach *UsbDetach `protobuf:"bytes,5,opt,name=usb_detach,json=usbDetach,proto3,oneof"`
}

type PlatformMessage_UsbListReq struct {
	UsbListReq *UsbDeviceListRequest `protobuf:"bytes,6,opt,name=usb_list_req,json=usbListReq,proto3,oneof"`
}

type PlatformMessage_UsbListResp struct {
	UsbListResp *UsbDeviceListResponse `protobuf:"bytes,7,opt,name=usb_list_resp,json=usbListResp,proto3,oneof"`
}

type PlatformMessage_UsbSelectReq struct {
	UsbSelectReq *UsbSelectRequest `protobuf:"bytes,8,opt,name=usb_select_req,json=usbSelectReq,proto3,oneof"`
}

type PlatformMessage_UsbSelectResp struct {
	UsbSelectResp *UsbSelectResponse `protobuf:"bytes,9,opt,name=usb_select_resp,json=usbSelectResp,proto3,oneof"`
}

type PlatformMessage_PttKeyReq struct {
	PttKeyReq *PttKeyRequest `protobuf:"bytes,10,opt,name=ptt_key_req,json=pttKeyReq,proto3,oneof"`
}

type PlatformMessage_PttUnkeyReq struct {
	PttUnkeyReq *PttUnkeyRequest `protobuf:"bytes,11,opt,name=ptt_unkey_req,json=pttUnkeyReq,proto3,oneof"`
}

type PlatformMessage_PttAck struct {
	PttAck *PttAck `protobuf:"bytes,12,opt,name=ptt_ack,json=pttAck,proto3,oneof"`
}

type PlatformMessage_AudioListReq struct {
	AudioListReq *AudioDeviceListRequest `protobuf:"bytes,13,opt,name=audio_list_req,json=audioListReq,proto3,oneof"`
}

type PlatformMessage_AudioListResp struct {
	AudioListResp *AudioDeviceListResponse `protobuf:"bytes,14,opt,name=audio_list_resp,json=audioListResp,proto3,oneof"`
}

type PlatformMessage_AudioRouteChanged struct {
	AudioRouteChanged *AudioRouteChanged `protobuf:"bytes,15,opt,name=audio_route_changed,json=audioRouteChanged,proto3,oneof"`
}

type PlatformMessage_Error struct {
	Error *Error `protobuf:"bytes,16,opt,name=error,proto3,oneof"`
}

type PlatformMessage_GnssStatus struct {
	GnssStatus *GnssStatusUpdate `protobuf:"bytes,17,opt,name=gnss_status,json=gnssStatus,proto3,oneof"` // server → client; pushed alongside GpsFix
}

type PlatformMessage_SerialOpen struct {
	SerialOpen *SerialOpen `protobuf:"bytes,18,opt,name=serial_open,json=serialOpen,proto3,oneof"`
}

type PlatformMessage_SerialOpenAck struct {
	SerialOpenAck *SerialOpenAck `protobuf:"bytes,19,opt,name=serial_open_ack,json=serialOpenAck,proto3,oneof"`
}

type PlatformMessage_SerialData struct {
	SerialData *SerialData `protobuf:"bytes,20,opt,name=serial_data,json=serialData,proto3,oneof"`
}

type PlatformMessage_SerialClose struct {
	SerialClose *SerialClose `protobuf:"bytes,21,opt,name=serial_close,json=serialClose,proto3,oneof"`
}

type PlatformMessage_SerialError struct {
	SerialError *SerialError `protobuf:"bytes,22,opt,name=serial_error,json=serialError,proto3,oneof"`
}

type PlatformMessage_BondedBtDevicesRequest struct {
	BondedBtDevicesRequest *BondedBtDevicesRequest `protobuf:"bytes,23,opt,name=bonded_bt_devices_request,json=bondedBtDevicesRequest,proto3,oneof"`
}

type PlatformMessage_BondedBtDevicesResponse struct {
	BondedBtDevicesResponse *BondedBtDevicesResponse `protobuf:"bytes,24,opt,name=bonded_bt_devices_response,json=bondedBtDevicesResponse,proto3,oneof"`
}

type PlatformMessage_AvailableUsbSerialDevicesRequest struct {
	AvailableUsbSerialDevicesRequest *AvailableUsbSerialDevicesRequest `protobuf:"bytes,25,opt,name=available_usb_serial_devices_request,json=availableUsbSerialDevicesRequest,proto3,oneof"`
}

type PlatformMessage_AvailableUsbSerialDevicesResponse struct {
	AvailableUsbSerialDevicesResponse *AvailableUsbSerialDevicesResponse `protobuf:"bytes,26,opt,name=available_usb_serial_devices_response,json=availableUsbSerialDevicesResponse,proto3,oneof"`
}

type PlatformMessage_BleScanRequest struct {
	BleScanRequest *BleScanRequest `protobuf:"bytes,27,opt,name=ble_scan_request,json=bleScanRequest,proto3,oneof"`
}

type PlatformMessage_BleScanResult struct {
	BleScanResult *BleScanResult `protobuf:"bytes,28,opt,name=ble_scan_result,json=bleScanResult,proto3,oneof"`
}

type PlatformMessage_BleScanError struct {
	BleScanError *BleScanError `protobuf:"bytes,29,opt,name=ble_scan_error,json=bleScanError,proto3,oneof"`
}

type PlatformMessage_BleScanStop struct {
	BleScanStop *BleScanStop `protobuf:"bytes,30,opt,name=ble_scan_stop,json=bleScanStop,proto3,oneof"`
}

func (*PlatformMessage_Hello) isPlatformMessage_Body() {}

func (*PlatformMessage_GpsFix) isPlatformMessage_Body() {}

func (*PlatformMessage_BatteryState) isPlatformMessage_Body() {}

func (*PlatformMessage_UsbAttach) isPlatformMessage_Body() {}

func (*PlatformMessage_UsbDetach) isPlatformMessage_Body() {}

func (*PlatformMessage_UsbListReq) isPlatformMessage_Body() {}

func (*PlatformMessage_UsbListResp) isPlatformMessage_Body() {}

func (*PlatformMessage_UsbSelectReq) isPlatformMessage_Body() {}

func (*PlatformMessage_UsbSelectResp) isPlatformMessage_Body() {}

func (*PlatformMessage_PttKeyReq) isPlatformMessage_Body() {}

func (*PlatformMessage_PttUnkeyReq) isPlatformMessage_Body() {}

func (*PlatformMessage_PttAck) isPlatformMessage_Body() {}

func (*PlatformMessage_AudioListReq) isPlatformMessage_Body() {}

func (*PlatformMessage_AudioListResp) isPlatformMessage_Body() {}

func (*PlatformMessage_AudioRouteChanged) isPlatformMessage_Body() {}

func (*PlatformMessage_Error) isPlatformMessage_Body() {}

func (*PlatformMessage_GnssStatus) isPlatformMessage_Body() {}

func (*PlatformMessage_SerialOpen) isPlatformMessage_Body() {}

func (*PlatformMessage_SerialOpenAck) isPlatformMessage_Body() {}

func (*PlatformMessage_SerialData) isPlatformMessage_Body() {}

func (*PlatformMessage_SerialClose) isPlatformMessage_Body() {}

func (*PlatformMessage_SerialError) isPlatformMessage_Body() {}

func (*PlatformMessage_BondedBtDevicesRequest) isPlatformMessage_Body() {}

func (*PlatformMessage_BondedBtDevicesResponse) isPlatformMessage_Body() {}

func (*PlatformMessage_AvailableUsbSerialDevicesRequest) isPlatformMessage_Body() {}

func (*PlatformMessage_AvailableUsbSerialDevicesResponse) isPlatformMessage_Body() {}

func (*PlatformMessage_BleScanRequest) isPlatformMessage_Body() {}

func (*PlatformMessage_BleScanResult) isPlatformMessage_Body() {}

func (*PlatformMessage_BleScanError) isPlatformMessage_Body() {}

func (*PlatformMessage_BleScanStop) isPlatformMessage_Body() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ClientVersion string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ServerVersion string                 `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"` // populated in the response only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Hello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Hello) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

type GpsFix struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Lat        float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon        float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	AltM       float64                `protobuf:"fixed64,3,opt,name=alt_m,json=altM,proto3" json:"alt_m,omitempty"`
	SpeedMps   float64                `protobuf:"fixed64,4,opt,name=speed_mps,json=speedMps,proto3" json:"speed_mps,omitempty"`
	CourseDeg  float64                `protobuf:"fixed64,5,opt,name=course_deg,json=courseDeg,proto3" json:"course_deg,omitempty"`
	TimeUnixMs int64                  `protobuf:"varint,6,opt,name=time_unix_ms,json=timeUnixMs,proto3" json:"time_unix_ms,omitempty"`
	Hdop       float64                `protobuf:"fixed64,7,opt,name=hdop,proto3" json:"hdop,omitempty"`
	NumSats    uint32                 `protobuf:"varint,8,opt,name=num_sats,json=numSats,proto3" json:"num_sats,omitempty"`
	Source     GpsSource              `protobuf:"varint,9,opt,name=source,proto3,enum=graywolf.platform.GpsSource" json:"source,omitempty"`
	// Horizontal accuracy radius in meters (Android Location.getAccuracy()).
	// 0 means "unknown / not provided" — desktop NMEA path leaves this 0.
	// (JSON consumers reading /api/gps/state must treat 0 as "unset", not
	// "perfect"; Android Location.accuracy never returns 0 in practice.)
	// Old clients ignore the field; old servers send 0. Schema version stays 1.
	AccuracyM float64 `protobuf:"fixed64,10,opt,name=accuracy_m,json=accuracyM,proto3" json:"accuracy_m,omitempty"`
	// Presence bits. Android Location exposes hasAltitude()/hasSpeed()/
	// hasBearing(); without these companion bools, the receiver cannot
	// distinguish a legitimate zero (stationary station, due-north course,
	// sea-level altitude) from "field absent". Default false on old senders.
	HasAlt        bool `protobuf:"varint,11,opt,name=has_alt,json=hasAlt,proto3" json:"has_alt,omitempty"`
	HasSpeed      bool `protobuf:"varint,12,opt,name=has_speed,json=hasSpeed,proto3" json:"has_speed,omitempty"`
	HasCourse     bool `protobuf:"varint,13,opt,name=has_course,json=hasCourse,proto3" json:"has_course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpsFix) Reset() {
	*x = GpsFix{}
	mi := &file_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpsFix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpsFix) ProtoMessage() {}

func (x *GpsFix) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpsFix.ProtoReflect.Descriptor instead.
func (*GpsFix) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{2}
}

func (x *GpsFix) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GpsFix) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GpsFix) GetAltM() float64 {
	if x != nil {
		return x.AltM
	}
	return 0
}

func (x *GpsFix) GetSpeedMps() float64 {
	if x != nil {
		return x.SpeedMps
	}
	return 0
}

func (x *GpsFix) GetCourseDeg() float64 {
	if x != nil {
		return x.CourseDeg
	}
	return 0
}

func (x *GpsFix) GetTimeUnixMs() int64 {
	if x != nil {
		return x.TimeUnixMs
	}
	return 0
}

func (x *GpsFix) GetHdop() float64 {
	if x != nil {
		return x.Hdop
	}
	return 0
}

func (x *GpsFix) GetNumSats() uint32 {
	if x != nil {
		return x.NumSats
	}
	return 0
}

func (x *GpsFix) GetSource() GpsSource {
	if x != nil {
		return x.Source
	}
	return GpsSource_GPS_SOURCE_UNKNOWN
}

func (x *GpsFix) GetAccuracyM() float64 {
	if x != nil {
		return x.AccuracyM
	}
	return 0
}

func (x *GpsFix) GetHasAlt() bool {
	if x != nil {
		return x.HasAlt
	}
	return false
}

func (x *GpsFix) GetHasSpeed() bool {
	if x != nil {
		return x.HasSpeed
	}
	return false
}

func (x *GpsFix) GetHasCourse() bool {
	if x != nil {
		return x.HasCourse
	}
	return false
}

type BatteryState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percent       float32                `protobuf:"fixed32,1,opt,name=percent,proto3" json:"percent,omitempty"`
	Charging      bool                   `protobuf:"varint,2,opt,name=charging,proto3" json:"charging,omitempty"`
	TempDecic     int32                  `protobuf:"varint,3,opt,name=temp_decic,json=tempDecic,proto3" json:"temp_decic,omitempty"` // tenths of a degree C
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatteryState) Reset() {
	*x = BatteryState{}
	mi := &file_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatteryState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryState) ProtoMessage() {}

func (x *BatteryState) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryState.ProtoReflect.Descriptor instead.
func (*BatteryState) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{3}
}

func (x *BatteryState) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *BatteryState) GetCharging() bool {
	if x != nil {
		return x.Charging
	}
	return false
}

func (x *BatteryState) GetTempDecic() int32 {
	if x != nil {
		return x.TempDecic
	}
	return 0
}

type UsbDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vid           uint32                 `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Product       string                 `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,4,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Serial        string                 `protobuf:"bytes,5,opt,name=serial,proto3" json:"serial,omitempty"`
	Classes       []UsbClass             `protobuf:"varint,6,rep,packed,name=classes,proto3,enum=graywolf.platform.UsbClass" json:"classes,omitempty"`
	DevicePath    string                 `protobuf:"bytes,7,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsbDevice) Reset() {
	*x = UsbDevice{}
	mi := &file_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsbDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsbDevice) ProtoMessage() {}

func (x *UsbDevice) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsbDevice.ProtoReflect.Descriptor instead.
func (*UsbDevice) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{4}
}

func (x *UsbDevice) GetVid() uint32 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *UsbDevice) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *UsbDevice) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *UsbDevice) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *UsbDevice) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *UsbDevice) GetClasses() []UsbClass {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *UsbDevice) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

type UsbAttach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *UsbDevice             `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsbAttach) Reset() {
	*x = UsbAttach{}
	mi := &file_platform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsbAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsbAttach) ProtoMessage() {}

func (x *UsbAttach) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsbAttach.ProtoReflect.Descriptor instead.
func (*UsbAttach) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{5}
}

func (x *UsbAttach) GetDevice() *UsbDevice {
	if x != nil {
		return x.Device
	}
	return nil
}

type UsbDetach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vid           uint32                 `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	DevicePath    string                 `protobuf:"bytes,3,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsbDetach) Reset() {
	*x = UsbDetach{}
	mi := &file_platform_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsbDetach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsbDetach) ProtoMessage() {}

func (x *UsbDetach) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsbDetach.ProtoReflect.Descriptor instead.
func (*UsbDetach) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{6}
}

func (x *UsbDetach) GetVid() uint32 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *UsbDetach) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *UsbDetach) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

type UsbDeviceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassFilter   UsbClass               `protobuf:"varint,1,opt,name=class_filter,json=classFilter,proto3,enum=graywolf.platform.UsbClass" json:"class_filter,omitempty"` // UNKNOWN = no filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsbDeviceListRequest) Reset() {
	*x = UsbDeviceListRequest{}
	mi := &file_platform_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsbDeviceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsbDeviceListRequest) ProtoMessage() {}

func (x *UsbDeviceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsbDeviceListRequest.ProtoReflect.Descriptor instead.
func (*UsbDeviceListRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{7}
}

func (x *UsbDeviceListRequest) GetClassFilter() UsbClass {
	if x != nil {
		return x.ClassFilter
	}
	return UsbClass_USB_CLASS_UNKNOWN
}

type UsbDeviceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*UsbDevice           `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsbDeviceListResponse) Reset() {
	*x = UsbDeviceListResponse{}
	mi := &file_platform_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsbDeviceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsbDeviceListResponse) ProtoMessage() {}

func (x *UsbDeviceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsbDeviceListResponse.ProtoReflect.Descriptor instead.
func (*UsbDeviceListResponse) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{8}
}

func (x *UsbDeviceListResponse) GetDevices() []*UsbDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type UsbSelectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vid           uint32                 `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsbSelectRequest) Reset() {
	*x = UsbSelectRequest{}
	mi := &file_platform_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsbSelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsbSelectRequest) ProtoMessage() {}

func (x *UsbSelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsbSelectRequest.ProtoReflect.Descriptor instead.
func (*UsbSelectRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{9}
}

func (x *UsbSelectRequest) GetVid() uint32 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *UsbSelectRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type UsbSelectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granted       bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	HandleId      string                 `protobuf:"bytes,2,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"` // opaque token used in subsequent PTT requests
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsbSelectResponse) Reset() {
	*x = UsbSelectResponse{}
	mi := &file_platform_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsbSelectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsbSelectResponse) ProtoMessage() {}

func (x *UsbSelectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsbSelectResponse.ProtoReflect.Descriptor instead.
func (*UsbSelectResponse) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{10}
}

func (x *UsbSelectResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *UsbSelectResponse) GetHandleId() string {
	if x != nil {
		return x.HandleId
	}
	return ""
}

func (x *UsbSelectResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PttKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        PttMethod              `protobuf:"varint,1,opt,name=method,proto3,enum=graywolf.platform.PttMethod" json:"method,omitempty"`
	HandleId      string                 `protobuf:"bytes,2,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PttKeyRequest) Reset() {
	*x = PttKeyRequest{}
	mi := &file_platform_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PttKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PttKeyRequest) ProtoMessage() {}

func (x *PttKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PttKeyRequest.ProtoReflect.Descriptor instead.
func (*PttKeyRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{11}
}

func (x *PttKeyRequest) GetMethod() PttMethod {
	if x != nil {
		return x.Method
	}
	return PttMethod_PTT_METHOD_UNKNOWN
}

func (x *PttKeyRequest) GetHandleId() string {
	if x != nil {
		return x.HandleId
	}
	return ""
}

type PttUnkeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        PttMethod              `protobuf:"varint,1,opt,name=method,proto3,enum=graywolf.platform.PttMethod" json:"method,omitempty"`
	HandleId      string                 `protobuf:"bytes,2,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PttUnkeyRequest) Reset() {
	*x = PttUnkeyRequest{}
	mi := &file_platform_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PttUnkeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PttUnkeyRequest) ProtoMessage() {}

func (x *PttUnkeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PttUnkeyRequest.ProtoReflect.Descriptor instead.
func (*PttUnkeyRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{12}
}

func (x *PttUnkeyRequest) GetMethod() PttMethod {
	if x != nil {
		return x.Method
	}
	return PttMethod_PTT_METHOD_UNKNOWN
}

func (x *PttUnkeyRequest) GetHandleId() string {
	if x != nil {
		return x.HandleId
	}
	return ""
}

type PttAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PttAck) Reset() {
	*x = PttAck{}
	mi := &file_platform_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PttAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PttAck) ProtoMessage() {}

func (x *PttAck) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PttAck.ProtoReflect.Descriptor instead.
func (*PttAck) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{13}
}

func (x *PttAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PttAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AudioDeviceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioDeviceListRequest) Reset() {
	*x = AudioDeviceListRequest{}
	mi := &file_platform_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioDeviceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioDeviceListRequest) ProtoMessage() {}

func (x *AudioDeviceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioDeviceListRequest.ProtoReflect.Descriptor instead.
func (*AudioDeviceListRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{14}
}

type AudioDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	IsInput       bool                   `protobuf:"varint,3,opt,name=is_input,json=isInput,proto3" json:"is_input,omitempty"`
	IsOutput      bool                   `protobuf:"varint,4,opt,name=is_output,json=isOutput,proto3" json:"is_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioDevice) Reset() {
	*x = AudioDevice{}
	mi := &file_platform_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioDevice) ProtoMessage() {}

func (x *AudioDevice) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioDevice.ProtoReflect.Descriptor instead.
func (*AudioDevice) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{15}
}

func (x *AudioDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AudioDevice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AudioDevice) GetIsInput() bool {
	if x != nil {
		return x.IsInput
	}
	return false
}

func (x *AudioDevice) GetIsOutput() bool {
	if x != nil {
		return x.IsOutput
	}
	return false
}

type AudioDeviceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*AudioDevice         `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioDeviceListResponse) Reset() {
	*x = AudioDeviceListResponse{}
	mi := &file_platform_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioDeviceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioDeviceListResponse) ProtoMessage() {}

func (x *AudioDeviceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioDeviceListResponse.ProtoReflect.Descriptor instead.
func (*AudioDeviceListResponse) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{16}
}

func (x *AudioDeviceListResponse) GetDevices() []*AudioDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type AudioRouteChanged struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentInputs  []*AudioDevice         `protobuf:"bytes,1,rep,name=current_inputs,json=currentInputs,proto3" json:"current_inputs,omitempty"`
	CurrentOutputs []*AudioDevice         `protobuf:"bytes,2,rep,name=current_outputs,json=currentOutputs,proto3" json:"current_outputs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AudioRouteChanged) Reset() {
	*x = AudioRouteChanged{}
	mi := &file_platform_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioRouteChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioRouteChanged) ProtoMessage() {}

func (x *AudioRouteChanged) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioRouteChanged.ProtoReflect.Descriptor instead.
func (*AudioRouteChanged) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{17}
}

func (x *AudioRouteChanged) GetCurrentInputs() []*AudioDevice {
	if x != nil {
		return x.CurrentInputs
	}
	return nil
}

func (x *AudioRouteChanged) GetCurrentOutputs() []*AudioDevice {
	if x != nil {
		return x.CurrentOutputs
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=graywolf.platform.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_platform_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{18}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_UNKNOWN
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SatInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Svid          uint32                 `protobuf:"varint,1,opt,name=svid,proto3" json:"svid,omitempty"`                       // satellite vehicle id
	Constellation string                 `protobuf:"bytes,2,opt,name=constellation,proto3" json:"constellation,omitempty"`      // "GPS" / "GLONASS" / "BEIDOU" / "GALILEO" / "QZSS" / "SBAS"
	Cn0Dbhz       float64                `protobuf:"fixed64,3,opt,name=cn0_dbhz,json=cn0Dbhz,proto3" json:"cn0_dbhz,omitempty"` // signal strength
	UsedInFix     bool                   `protobuf:"varint,4,opt,name=used_in_fix,json=usedInFix,proto3" json:"used_in_fix,omitempty"`
	ElevationDeg  float64                `protobuf:"fixed64,5,opt,name=elevation_deg,json=elevationDeg,proto3" json:"elevation_deg,omitempty"`
	AzimuthDeg    float64                `protobuf:"fixed64,6,opt,name=azimuth_deg,json=azimuthDeg,proto3" json:"azimuth_deg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatInfo) Reset() {
	*x = SatInfo{}
	mi := &file_platform_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatInfo) ProtoMessage() {}

func (x *SatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatInfo.ProtoReflect.Descriptor instead.
func (*SatInfo) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{19}
}

func (x *SatInfo) GetSvid() uint32 {
	if x != nil {
		return x.Svid
	}
	return 0
}

func (x *SatInfo) GetConstellation() string {
	if x != nil {
		return x.Constellation
	}
	return ""
}

func (x *SatInfo) GetCn0Dbhz() float64 {
	if x != nil {
		return x.Cn0Dbhz
	}
	return 0
}

func (x *SatInfo) GetUsedInFix() bool {
	if x != nil {
		return x.UsedInFix
	}
	return false
}

func (x *SatInfo) GetElevationDeg() float64 {
	if x != nil {
		return x.ElevationDeg
	}
	return 0
}

func (x *SatInfo) GetAzimuthDeg() float64 {
	if x != nil {
		return x.AzimuthDeg
	}
	return 0
}

type GnssStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SatsInView    uint32                 `protobuf:"varint,1,opt,name=sats_in_view,json=satsInView,proto3" json:"sats_in_view,omitempty"`
	SatsUsed      uint32                 `protobuf:"varint,2,opt,name=sats_used,json=satsUsed,proto3" json:"sats_used,omitempty"`
	Sats          []*SatInfo             `protobuf:"bytes,3,rep,name=sats,proto3" json:"sats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GnssStatusUpdate) Reset() {
	*x = GnssStatusUpdate{}
	mi := &file_platform_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GnssStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GnssStatusUpdate) ProtoMessage() {}

func (x *GnssStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GnssStatusUpdate.ProtoReflect.Descriptor instead.
func (*GnssStatusUpdate) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{20}
}

func (x *GnssStatusUpdate) GetSatsInView() uint32 {
	if x != nil {
		return x.SatsInView
	}
	return 0
}

func (x *GnssStatusUpdate) GetSatsUsed() uint32 {
	if x != nil {
		return x.SatsUsed
	}
	return 0
}

func (x *GnssStatusUpdate) GetSats() []*SatInfo {
	if x != nil {
		return x.Sats
	}
	return nil
}

type SerialOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        uint32                 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Kind          SerialKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=graywolf.platform.SerialKind" json:"kind,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"` // bluetooth: MAC ("AA:BB:CC:DD:EE:FF"); usb: "vid:pid" hex ("2341:0043")
	Baud          uint32                 `protobuf:"varint,4,opt,name=baud,proto3" json:"baud,omitempty"`      // usb: line speed (required); ignored by bluetooth
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerialOpen) Reset() {
	*x = SerialOpen{}
	mi := &file_platform_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerialOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialOpen) ProtoMessage() {}

func (x *SerialOpen) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialOpen.ProtoReflect.Descriptor instead.
func (*SerialOpen) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{21}
}

func (x *SerialOpen) GetHandle() uint32 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *SerialOpen) GetKind() SerialKind {
	if x != nil {
		return x.Kind
	}
	return SerialKind_SERIAL_KIND_UNSPECIFIED
}

func (x *SerialOpen) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SerialOpen) GetBaud() uint32 {
	if x != nil {
		return x.Baud
	}
	return 0
}

type SerialOpenAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        uint32                 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerialOpenAck) Reset() {
	*x = SerialOpenAck{}
	mi := &file_platform_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerialOpenAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialOpenAck) ProtoMessage() {}

func (x *SerialOpenAck) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialOpenAck.ProtoReflect.Descriptor instead.
func (*SerialOpenAck) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{22}
}

func (x *SerialOpenAck) GetHandle() uint32 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *SerialOpenAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SerialOpenAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SerialData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        uint32                 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerialData) Reset() {
	*x = SerialData{}
	mi := &file_platform_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerialData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialData) ProtoMessage() {}

func (x *SerialData) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialData.ProtoReflect.Descriptor instead.
func (*SerialData) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{23}
}

func (x *SerialData) GetHandle() uint32 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *SerialData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SerialClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        uint32                 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerialClose) Reset() {
	*x = SerialClose{}
	mi := &file_platform_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerialClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialClose) ProtoMessage() {}

func (x *SerialClose) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialClose.ProtoReflect.Descriptor instead.
func (*SerialClose) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{24}
}

func (x *SerialClose) GetHandle() uint32 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *SerialClose) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SerialError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        uint32                 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"` // bond_lost | permission_denied | rfcomm_closed | io_error | not_bonded
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerialError) Reset() {
	*x = SerialError{}
	mi := &file_platform_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerialError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialError) ProtoMessage() {}

func (x *SerialError) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialError.ProtoReflect.Descriptor instead.
func (*SerialError) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{25}
}

func (x *SerialError) GetHandle() uint32 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *SerialError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SerialError) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type BondedBtDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BondedBtDevicesRequest) Reset() {
	*x = BondedBtDevicesRequest{}
	mi := &file_platform_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BondedBtDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BondedBtDevicesRequest) ProtoMessage() {}

func (x *BondedBtDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BondedBtDevicesRequest.ProtoReflect.Descriptor instead.
func (*BondedBtDevicesRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{26}
}

type BondedBtDevicesResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Devices       []*BondedBtDevicesResponse_Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BondedBtDevicesResponse) Reset() {
	*x = BondedBtDevicesResponse{}
	mi := &file_platform_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BondedBtDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BondedBtDevicesResponse) ProtoMessage() {}

func (x *BondedBtDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BondedBtDevicesResponse.ProtoReflect.Descriptor instead.
func (*BondedBtDevicesResponse) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{27}
}

func (x *BondedBtDevicesResponse) GetDevices() []*BondedBtDevicesResponse_Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type AvailableUsbSerialDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableUsbSerialDevicesRequest) Reset() {
	*x = AvailableUsbSerialDevicesRequest{}
	mi := &file_platform_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableUsbSerialDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableUsbSerialDevicesRequest) ProtoMessage() {}

func (x *AvailableUsbSerialDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableUsbSerialDevicesRequest.ProtoReflect.Descriptor instead.
func (*AvailableUsbSerialDevicesRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{28}
}

type AvailableUsbSerialDevicesResponse struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	Devices       []*AvailableUsbSerialDevicesResponse_Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableUsbSerialDevicesResponse) Reset() {
	*x = AvailableUsbSerialDevicesResponse{}
	mi := &file_platform_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableUsbSerialDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableUsbSerialDevicesResponse) ProtoMessage() {}

func (x *AvailableUsbSerialDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableUsbSerialDevicesResponse.ProtoReflect.Descriptor instead.
func (*AvailableUsbSerialDevicesResponse) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{29}
}

func (x *AvailableUsbSerialDevicesResponse) GetDevices() []*AvailableUsbSerialDevicesResponse_Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type BleScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BleScanRequest) Reset() {
	*x = BleScanRequest{}
	mi := &file_platform_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BleScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BleScanRequest) ProtoMessage() {}

func (x *BleScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BleScanRequest.ProtoReflect.Descriptor instead.
func (*BleScanRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{30}
}

type BleScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`  // BLE MAC address
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`  // advertised name (may be empty)
	Rssi          int32                  `protobuf:"varint,3,opt,name=rssi,proto3" json:"rssi,omitempty"` // signal strength in dBm
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BleScanResult) Reset() {
	*x = BleScanResult{}
	mi := &file_platform_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BleScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BleScanResult) ProtoMessage() {}

func (x *BleScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BleScanResult.ProtoReflect.Descriptor instead.
func (*BleScanResult) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{31}
}

func (x *BleScanResult) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *BleScanResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BleScanResult) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

type BleScanError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`     // short error token (e.g. "permission_denied", "scanner_unavailable")
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"` // human-readable detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BleScanError) Reset() {
	*x = BleScanError{}
	mi := &file_platform_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BleScanError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BleScanError) ProtoMessage() {}

func (x *BleScanError) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BleScanError.ProtoReflect.Descriptor instead.
func (*BleScanError) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{32}
}

func (x *BleScanError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BleScanError) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type BleScanStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BleScanStop) Reset() {
	*x = BleScanStop{}
	mi := &file_platform_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BleScanStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BleScanStop) ProtoMessage() {}

func (x *BleScanStop) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BleScanStop.ProtoReflect.Descriptor instead.
func (*BleScanStop) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{33}
}

type BondedBtDevicesResponse_Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           string                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BondedBtDevicesResponse_Device) Reset() {
	*x = BondedBtDevicesResponse_Device{}
	mi := &file_platform_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BondedBtDevicesResponse_Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BondedBtDevicesResponse_Device) ProtoMessage() {}

func (x *BondedBtDevicesResponse_Device) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BondedBtDevicesResponse_Device.ProtoReflect.Descriptor instead.
func (*BondedBtDevicesResponse_Device) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{27, 0}
}

func (x *BondedBtDevicesResponse_Device) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *BondedBtDevicesResponse_Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AvailableUsbSerialDevicesResponse_Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VidPid        string                 `protobuf:"bytes,1,opt,name=vid_pid,json=vidPid,proto3" json:"vid_pid,omitempty"` // "2341:0043"
	Product       string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,3,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	HasPermission bool                   `protobuf:"varint,4,opt,name=has_permission,json=hasPermission,proto3" json:"has_permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableUsbSerialDevicesResponse_Device) Reset() {
	*x = AvailableUsbSerialDevicesResponse_Device{}
	mi := &file_platform_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableUsbSerialDevicesResponse_Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableUsbSerialDevicesResponse_Device) ProtoMessage() {}

func (x *AvailableUsbSerialDevicesResponse_Device) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableUsbSerialDevicesResponse_Device.ProtoReflect.Descriptor instead.
func (*AvailableUsbSerialDevicesResponse_Device) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{29, 0}
}

func (x *AvailableUsbSerialDevicesResponse_Device) GetVidPid() string {
	if x != nil {
		return x.VidPid
	}
	return ""
}

func (x *AvailableUsbSerialDevicesResponse_Device) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *AvailableUsbSerialDevicesResponse_Device) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *AvailableUsbSerialDevicesResponse_Device) GetHasPermission() bool {
	if x != nil {
		return x.HasPermission
	}
	return false
}

var File_platform_proto protoreflect.FileDescriptor

const file_platform_proto_rawDesc = "" +
	"\n" +
	"\x0eplatform.proto\x12\x11graywolf.platform\"\xaa\x12\n" +
	"\x0fPlatformMessage\x120\n" +
	"\x05hello\x18\x01 \x01(\v2\x18.graywolf.platform.HelloH\x00R\x05hello\x124\n" +
	"\agps_fix\x18\x02 \x01(\v2\x19.graywolf.platform.GpsFixH\x00R\x06gpsFix\x12F\n" +
	"\rbattery_state\x18\x03 \x01(\v2\x1f.graywolf.platform.BatteryStateH\x00R\fbatteryState\x12=\n" +
	"\n" +
	"usb_attach\x18\x04 \x01(\v2\x1c.graywolf.platform.UsbAttachH\x00R\tusbAttach\x12=\n" +
	"\n" +
	"usb_detach\x18\x05 \x01(\v2\x1c.graywolf.platform.UsbDetachH\x00R\tusbDetach\x12K\n" +
	"\fusb_list_req\x18\x06 \x01(\v2'.graywolf.platform.UsbDeviceListRequestH\x00R\n" +
	"usbListReq\x12N\n" +
	"\rusb_list_resp\x18\a \x01(\v2(.graywolf.platform.UsbDeviceListResponseH\x00R\vusbListResp\x12K\n" +
	"\x0eusb_select_req\x18\b \x01(\v2#.graywolf.platform.UsbSelectRequestH\x00R\fusbSelectReq\x12N\n" +
	"\x0fusb_select_resp\x18\t \x01(\v2$.graywolf.platform.UsbSelectResponseH\x00R\rusbSelectResp\x12B\n" +
	"\vptt_key_req\x18\n" +
	" \x01(\v2 .graywolf.platform.PttKeyRequestH\x00R\tpttKeyReq\x12H\n" +
	"\rptt_unkey_req\x18\v \x01(\v2\".graywolf.platform.PttUnkeyRequestH\x00R\vpttUnkeyReq\x124\n" +
	"\aptt_ack\x18\f \x01(\v2\x19.graywolf.platform.PttAckH\x00R\x06pttAck\x12Q\n" +
	"\x0eaudio_list_req\x18\r \x01(\v2).graywolf.platform.AudioDeviceListRequestH\x00R\faudioListReq\x12T\n" +
	"\x0faudio_list_resp\x18\x0e \x01(\v2*.graywolf.platform.AudioDeviceListResponseH\x00R\raudioListResp\x12V\n" +
	"\x13audio_route_changed\x18\x0f \x01(\v2$.graywolf.platform.AudioRouteChangedH\x00R\x11audioRouteChanged\x120\n" +
	"\x05error\x18\x10 \x01(\v2\x18.graywolf.platform.ErrorH\x00R\x05error\x12F\n" +
	"\vgnss_status\x18\x11 \x01(\v2#.graywolf.platform.GnssStatusUpdateH\x00R\n" +
	"gnssStatus\x12@\n" +
	"\vserial_open\x18\x12 \x01(\v2\x1d.graywolf.platform.SerialOpenH\x00R\n" +
	"serialOpen\x12J\n" +
	"\x0fserial_open_ack\x18\x13 \x01(\v2 .graywolf.platform.SerialOpenAckH\x00R\rserialOpenAck\x12@\n" +
	"\vserial_data\x18\x14 \x01(\v2\x1d.graywolf.platform.SerialDataH\x00R\n" +
	"serialData\x12C\n" +
	"\fserial_close\x18\x15 \x01(\v2\x1e.graywolf.platform.SerialCloseH\x00R\vserialClose\x12C\n" +
	"\fserial_error\x18\x16 \x01(\v2\x1e.graywolf.platform.SerialErrorH\x00R\vserialError\x12f\n" +
	"\x19bonded_bt_devices_request\x18\x17 \x01(\v2).graywolf.platform.BondedBtDevicesRequestH\x00R\x16bondedBtDevicesRequest\x12i\n" +
	"\x1abonded_bt_devices_response\x18\x18 \x01(\v2*.graywolf.platform.BondedBtDevicesResponseH\x00R\x17bondedBtDevicesResponse\x12\x85\x01\n" +
	"$available_usb_serial_devices_request\x18\x19 \x01(\v23.graywolf.platform.AvailableUsbSerialDevicesRequestH\x00R availableUsbSerialDevicesRequest\x12\x88\x01\n" +
	"%available_usb_serial_devices_response\x18\x1a \x01(\v24.graywolf.platform.AvailableUsbSerialDevicesResponseH\x00R!availableUsbSerialDevicesResponse\x12M\n" +
	"\x10ble_scan_request\x18\x1b \x01(\v2!.graywolf.platform.BleScanRequestH\x00R\x0ebleScanRequest\x12J\n" +
	"\x0fble_scan_result\x18\x1c \x01(\v2 .graywolf.platform.BleScanResultH\x00R\rbleScanResult\x12G\n" +
	"\x0eble_scan_error\x18\x1d \x01(\v2\x1f.graywolf.platform.BleScanErrorH\x00R\fbleScanError\x12D\n" +
	"\rble_scan_stop\x18\x1e \x01(\v2\x1e.graywolf.platform.BleScanStopH\x00R\vbleScanStopB\x06\n" +
	"\x04body\"|\n" +
	"\x05Hello\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\x12%\n" +
	"\x0eserver_version\x18\x03 \x01(\tR\rserverVersion\"\xf8\x02\n" +
	"\x06GpsFix\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x13\n" +
	"\x05alt_m\x18\x03 \x01(\x01R\x04altM\x12\x1b\n" +
	"\tspeed_mps\x18\x04 \x01(\x01R\bspeedMps\x12\x1d\n" +
	"\n" +
	"course_deg\x18\x05 \x01(\x01R\tcourseDeg\x12 \n" +
	"\ftime_unix_ms\x18\x06 \x01(\x03R\n" +
	"timeUnixMs\x12\x12\n" +
	"\x04hdop\x18\a \x01(\x01R\x04hdop\x12\x19\n" +
	"\bnum_sats\x18\b \x01(\rR\anumSats\x124\n" +
	"\x06source\x18\t \x01(\x0e2\x1c.graywolf.platform.GpsSourceR\x06source\x12\x1d\n" +
	"\n" +
	"accuracy_m\x18\n" +
	" \x01(\x01R\taccuracyM\x12\x17\n" +
	"\ahas_alt\x18\v \x01(\bR\x06hasAlt\x12\x1b\n" +
	"\thas_speed\x18\f \x01(\bR\bhasSpeed\x12\x1d\n" +
	"\n" +
	"has_course\x18\r \x01(\bR\thasCourse\"c\n" +
	"\fBatteryState\x12\x18\n" +
	"\apercent\x18\x01 \x01(\x02R\apercent\x12\x1a\n" +
	"\bcharging\x18\x02 \x01(\bR\bcharging\x12\x1d\n" +
	"\n" +
	"temp_decic\x18\x03 \x01(\x05R\ttempDecic\"\xdd\x01\n" +
	"\tUsbDevice\x12\x10\n" +
	"\x03vid\x18\x01 \x01(\rR\x03vid\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x18\n" +
	"\aproduct\x18\x03 \x01(\tR\aproduct\x12\"\n" +
	"\fmanufacturer\x18\x04 \x01(\tR\fmanufacturer\x12\x16\n" +
	"\x06serial\x18\x05 \x01(\tR\x06serial\x125\n" +
	"\aclasses\x18\x06 \x03(\x0e2\x1b.graywolf.platform.UsbClassR\aclasses\x12\x1f\n" +
	"\vdevice_path\x18\a \x01(\tR\n" +
	"devicePath\"A\n" +
	"\tUsbAttach\x124\n" +
	"\x06device\x18\x01 \x01(\v2\x1c.graywolf.platform.UsbDeviceR\x06device\"P\n" +
	"\tUsbDetach\x12\x10\n" +
	"\x03vid\x18\x01 \x01(\rR\x03vid\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x1f\n" +
	"\vdevice_path\x18\x03 \x01(\tR\n" +
	"devicePath\"V\n" +
	"\x14UsbDeviceListRequest\x12>\n" +
	"\fclass_filter\x18\x01 \x01(\x0e2\x1b.graywolf.platform.UsbClassR\vclassFilter\"O\n" +
	"\x15UsbDeviceListResponse\x126\n" +
	"\adevices\x18\x01 \x03(\v2\x1c.graywolf.platform.UsbDeviceR\adevices\"6\n" +
	"\x10UsbSelectRequest\x12\x10\n" +
	"\x03vid\x18\x01 \x01(\rR\x03vid\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\"o\n" +
	"\x11UsbSelectResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12\x1b\n" +
	"\thandle_id\x18\x02 \x01(\tR\bhandleId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"b\n" +
	"\rPttKeyRequest\x124\n" +
	"\x06method\x18\x01 \x01(\x0e2\x1c.graywolf.platform.PttMethodR\x06method\x12\x1b\n" +
	"\thandle_id\x18\x02 \x01(\tR\bhandleId\"d\n" +
	"\x0fPttUnkeyRequest\x124\n" +
	"\x06method\x18\x01 \x01(\x0e2\x1c.graywolf.platform.PttMethodR\x06method\x12\x1b\n" +
	"\thandle_id\x18\x02 \x01(\tR\bhandleId\"=\n" +
	"\x06PttAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x18\n" +
	"\x16AudioDeviceListRequest\"i\n" +
	"\vAudioDevice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x19\n" +
	"\bis_input\x18\x03 \x01(\bR\aisInput\x12\x1b\n" +
	"\tis_output\x18\x04 \x01(\bR\bisOutput\"S\n" +
	"\x17AudioDeviceListResponse\x128\n" +
	"\adevices\x18\x01 \x03(\v2\x1e.graywolf.platform.AudioDeviceR\adevices\"\xa3\x01\n" +
	"\x11AudioRouteChanged\x12E\n" +
	"\x0ecurrent_inputs\x18\x01 \x03(\v2\x1e.graywolf.platform.AudioDeviceR\rcurrentInputs\x12G\n" +
	"\x0fcurrent_outputs\x18\x02 \x03(\v2\x1e.graywolf.platform.AudioDeviceR\x0ecurrentOutputs\"S\n" +
	"\x05Error\x120\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1c.graywolf.platform.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc4\x01\n" +
	"\aSatInfo\x12\x12\n" +
	"\x04svid\x18\x01 \x01(\rR\x04svid\x12$\n" +
	"\rconstellation\x18\x02 \x01(\tR\rconstellation\x12\x19\n" +
	"\bcn0_dbhz\x18\x03 \x01(\x01R\acn0Dbhz\x12\x1e\n" +
	"\vused_in_fix\x18\x04 \x01(\bR\tusedInFix\x12#\n" +
	"\relevation_deg\x18\x05 \x01(\x01R\felevationDeg\x12\x1f\n" +
	"\vazimuth_deg\x18\x06 \x01(\x01R\n" +
	"azimuthDeg\"\x81\x01\n" +
	"\x10GnssStatusUpdate\x12 \n" +
	"\fsats_in_view\x18\x01 \x01(\rR\n" +
	"satsInView\x12\x1b\n" +
	"\tsats_used\x18\x02 \x01(\rR\bsatsUsed\x12.\n" +
	"\x04sats\x18\x03 \x03(\v2\x1a.graywolf.platform.SatInfoR\x04sats\"\x85\x01\n" +
	"\n" +
	"SerialOpen\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\rR\x06handle\x121\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1d.graywolf.platform.SerialKindR\x04kind\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04baud\x18\x04 \x01(\rR\x04baud\"M\n" +
	"\rSerialOpenAck\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\rR\x06handle\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"8\n" +
	"\n" +
	"SerialData\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\rR\x06handle\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"=\n" +
	"\vSerialClose\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\rR\x06handle\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"Q\n" +
	"\vSerialError\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\rR\x06handle\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\x18\n" +
	"\x16BondedBtDevicesRequest\"\x96\x01\n" +
	"\x17BondedBtDevicesResponse\x12K\n" +
	"\adevices\x18\x01 \x03(\v21.graywolf.platform.BondedBtDevicesResponse.DeviceR\adevices\x1a.\n" +
	"\x06Device\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03mac\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\"\n" +
	" AvailableUsbSerialDevicesRequest\"\x83\x02\n" +
	"!AvailableUsbSerialDevicesResponse\x12U\n" +
	"\adevices\x18\x01 \x03(\v2;.graywolf.platform.AvailableUsbSerialDevicesResponse.DeviceR\adevices\x1a\x86\x01\n" +
	"\x06Device\x12\x17\n" +
	"\avid_pid\x18\x01 \x01(\tR\x06vidPid\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\"\n" +
	"\fmanufacturer\x18\x03 \x01(\tR\fmanufacturer\x12%\n" +
	"\x0ehas_permission\x18\x04 \x01(\bR\rhasPermission\"\x10\n" +
	"\x0eBleScanRequest\"K\n" +
	"\rBleScanResult\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04rssi\x18\x03 \x01(\x05R\x04rssi\":\n" +
	"\fBleScanError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\r\n" +
	"\vBleScanStop*}\n" +
	"\tGpsSource\x12\x16\n" +
	"\x12GPS_SOURCE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18GPS_SOURCE_ANDROID_FUSED\x10\x01\x12\x1a\n" +
	"\x16GPS_SOURCE_ANDROID_GPS\x10\x02\x12\x1e\n" +
	"\x1aGPS_SOURCE_ANDROID_NETWORK\x10\x03*v\n" +
	"\bUsbClass\x12\x15\n" +
	"\x11USB_CLASS_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fUSB_CLASS_AUDIO\x10\x01\x12\x11\n" +
	"\rUSB_CLASS_HID\x10\x02\x12\x15\n" +
	"\x11USB_CLASS_CDC_ACM\x10\x03\x12\x14\n" +
	"\x10USB_CLASS_VENDOR\x10\x04*\xa7\x01\n" +
	"\tPttMethod\x12\x16\n" +
	"\x12PTT_METHOD_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16PTT_METHOD_CP2102N_RTS\x10\x01\x12\x18\n" +
	"\x14PTT_METHOD_CM108_HID\x10\x02\x12\x1b\n" +
	"\x17PTT_METHOD_AIOC_CDC_DTR\x10\x03\x12\x12\n" +
	"\x0ePTT_METHOD_VOX\x10\x04\x12\x1b\n" +
	"\x17PTT_METHOD_DIGIRIG_TONE\x10\x05*\xb6\x01\n" +
	"\tErrorCode\x12\x11\n" +
	"\rERROR_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15ERROR_NOT_IMPLEMENTED\x10\x01\x12\x19\n" +
	"\x15ERROR_SCHEMA_MISMATCH\x10\x02\x12\x1a\n" +
	"\x16ERROR_INVALID_ARGUMENT\x10\x03\x12\x1b\n" +
	"\x17ERROR_PERMISSION_DENIED\x10\x04\x12\x13\n" +
	"\x0fERROR_NOT_FOUND\x10\x05\x12\x12\n" +
	"\x0eERROR_INTERNAL\x10\x06*n\n" +
	"\n" +
	"SerialKind\x12\x1b\n" +
	"\x17SERIAL_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SERIAL_KIND_BLUETOOTH\x10\x01\x12\x13\n" +
	"\x0fSERIAL_KIND_USB\x10\x02\x12\x13\n" +
	"\x0fSERIAL_KIND_BLE\x10\x03Bc\n" +
	"\x1fcom.nw5w.graywolf.platformprotoP\x01Z>github.com/chrissnell/graywolf/pkg/platformproto;platformprotob\x06proto3"

var (
	file_platform_proto_rawDescOnce sync.Once
	file_platform_proto_rawDescData []byte
)

func file_platform_proto_rawDescGZIP() []byte {
	file_platform_proto_rawDescOnce.Do(func() {
		file_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_proto_rawDesc), len(file_platform_proto_rawDesc)))
	})
	return file_platform_proto_rawDescData
}

var file_platform_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_platform_proto_goTypes = []any{
	(GpsSource)(0),                                   // 0: graywolf.platform.GpsSource
	(UsbClass)(0),                                    // 1: graywolf.platform.UsbClass
	(PttMethod)(0),                                   // 2: graywolf.platform.PttMethod
	(ErrorCode)(0),                                   // 3: graywolf.platform.ErrorCode
	(SerialKind)(0),                                  // 4: graywolf.platform.SerialKind
	(*PlatformMessage)(nil),                          // 5: graywolf.platform.PlatformMessage
	(*Hello)(nil),                                    // 6: graywolf.platform.Hello
	(*GpsFix)(nil),                                   // 7: graywolf.platform.GpsFix
	(*BatteryState)(nil),                             // 8: graywolf.platform.BatteryState
	(*UsbDevice)(nil),                                // 9: graywolf.platform.UsbDevice
	(*UsbAttach)(nil),                                // 10: graywolf.platform.UsbAttach
	(*UsbDetach)(nil),                                // 11: graywolf.platform.UsbDetach
	(*UsbDeviceListRequest)(nil),                     // 12: graywolf.platform.UsbDeviceListRequest
	(*UsbDeviceListResponse)(nil),                    // 13: graywolf.platform.UsbDeviceListResponse
	(*UsbSelectRequest)(nil),                         // 14: graywolf.platform.UsbSelectRequest
	(*UsbSelectResponse)(nil),                        // 15: graywolf.platform.UsbSelectResponse
	(*PttKeyRequest)(nil),                            // 16: graywolf.platform.PttKeyRequest
	(*PttUnkeyRequest)(nil),                          // 17: graywolf.platform.PttUnkeyRequest
	(*PttAck)(nil),                                   // 18: graywolf.platform.PttAck
	(*AudioDeviceListRequest)(nil),                   // 19: graywolf.platform.AudioDeviceListRequest
	(*AudioDevice)(nil),                              // 20: graywolf.platform.AudioDevice
	(*AudioDeviceListResponse)(nil),                  // 21: graywolf.platform.AudioDeviceListResponse
	(*AudioRouteChanged)(nil),                        // 22: graywolf.platform.AudioRouteChanged
	(*Error)(nil),                                    // 23: graywolf.platform.Error
	(*SatInfo)(nil),                                  // 24: graywolf.platform.SatInfo
	(*GnssStatusUpdate)(nil),                         // 25: graywolf.platform.GnssStatusUpdate
	(*SerialOpen)(nil),                               // 26: graywolf.platform.SerialOpen
	(*SerialOpenAck)(nil),                            // 27: graywolf.platform.SerialOpenAck
	(*SerialData)(nil),                               // 28: graywolf.platform.SerialData
	(*SerialClose)(nil),                              // 29: graywolf.platform.SerialClose
	(*SerialError)(nil),                              // 30: graywolf.platform.SerialError
	(*BondedBtDevicesRequest)(nil),                   // 31: graywolf.platform.BondedBtDevicesRequest
	(*BondedBtDevicesResponse)(nil),                  // 32: graywolf.platform.BondedBtDevicesResponse
	(*AvailableUsbSerialDevicesRequest)(nil),         // 33: graywolf.platform.AvailableUsbSerialDevicesRequest
	(*AvailableUsbSerialDevicesResponse)(nil),        // 34: graywolf.platform.AvailableUsbSerialDevicesResponse
	(*BleScanRequest)(nil),                           // 35: graywolf.platform.BleScanRequest
	(*BleScanResult)(nil),                            // 36: graywolf.platform.BleScanResult
	(*BleScanError)(nil),                             // 37: graywolf.platform.BleScanError
	(*BleScanStop)(nil),                              // 38: graywolf.platform.BleScanStop
	(*BondedBtDevicesResponse_Device)(nil),           // 39: graywolf.platform.BondedBtDevicesResponse.Device
	(*AvailableUsbSerialDevicesResponse_Device)(nil), // 40: graywolf.platform.AvailableUsbSerialDevicesResponse.Device
}
var file_platform_proto_depIdxs = []int32{
	6,  // 0: graywolf.platform.PlatformMessage.hello:type_name -> graywolf.platform.Hello
	7,  // 1: graywolf.platform.PlatformMessage.gps_fix:type_name -> graywolf.platform.GpsFix
	8,  // 2: graywolf.platform.PlatformMessage.battery_state:type_name -> graywolf.platform.BatteryState
	10, // 3: graywolf.platform.PlatformMessage.usb_attach:type_name -> graywolf.platform.UsbAttach
	11, // 4: graywolf.platform.PlatformMessage.usb_detach:type_name -> graywolf.platform.UsbDetach
	12, // 5: graywolf.platform.PlatformMessage.usb_list_req:type_name -> graywolf.platform.UsbDeviceListRequest
	13, // 6: graywolf.platform.PlatformMessage.usb_list_resp:type_name -> graywolf.platform.UsbDeviceListResponse
	14, // 7: graywolf.platform.PlatformMessage.usb_select_req:type_name -> graywolf.platform.UsbSelectRequest
	15, // 8: graywolf.platform.PlatformMessage.usb_select_resp:type_name -> graywolf.platform.UsbSelectResponse
	16, // 9: graywolf.platform.PlatformMessage.ptt_key_req:type_name -> graywolf.platform.PttKeyRequest
	17, // 10: graywolf.platform.PlatformMessage.ptt_unkey_req:type_name -> graywolf.platform.PttUnkeyRequest
	18, // 11: graywolf.platform.PlatformMessage.ptt_ack:type_name -> graywolf.platform.PttAck
	19, // 12: graywolf.platform.PlatformMessage.audio_list_req:type_name -> graywolf.platform.AudioDeviceListRequest
	21, // 13: graywolf.platform.PlatformMessage.audio_list_resp:type_name -> graywolf.platform.AudioDeviceListResponse
	22, // 14: graywolf.platform.PlatformMessage.audio_route_changed:type_name -> graywolf.platform.AudioRouteChanged
	23, // 15: graywolf.platform.PlatformMessage.error:type_name -> graywolf.platform.Error
	25, // 16: graywolf.platform.PlatformMessage.gnss_status:type_name -> graywolf.platform.GnssStatusUpdate
	26, // 17: graywolf.platform.PlatformMessage.serial_open:type_name -> graywolf.platform.SerialOpen
	27, // 18: graywolf.platform.PlatformMessage.serial_open_ack:type_name -> graywolf.platform.SerialOpenAck
	28, // 19: graywolf.platform.PlatformMessage.serial_data:type_name -> graywolf.platform.SerialData
	29, // 20: graywolf.platform.PlatformMessage.serial_close:type_name -> graywolf.platform.SerialClose
	30, // 21: graywolf.platform.PlatformMessage.serial_error:type_name -> graywolf.platform.SerialError
	31, // 22: graywolf.platform.PlatformMessage.bonded_bt_devices_request:type_name -> graywolf.platform.BondedBtDevicesRequest
	32, // 23: graywolf.platform.PlatformMessage.bonded_bt_devices_response:type_name -> graywolf.platform.BondedBtDevicesResponse
	33, // 24: graywolf.platform.PlatformMessage.available_usb_serial_devices_request:type_name -> graywolf.platform.AvailableUsbSerialDevicesRequest
	34, // 25: graywolf.platform.PlatformMessage.available_usb_serial_devices_response:type_name -> graywolf.platform.AvailableUsbSerialDevicesResponse
	35, // 26: graywolf.platform.PlatformMessage.ble_scan_request:type_name -> graywolf.platform.BleScanRequest
	36, // 27: graywolf.platform.PlatformMessage.ble_scan_result:type_name -> graywolf.platform.BleScanResult
	37, // 28: graywolf.platform.PlatformMessage.ble_scan_error:type_name -> graywolf.platform.BleScanError
	38, // 29: graywolf.platform.PlatformMessage.ble_scan_stop:type_name -> graywolf.platform.BleScanStop
	0,  // 30: graywolf.platform.GpsFix.source:type_name -> graywolf.platform.GpsSource
	1,  // 31: graywolf.platform.UsbDevice.classes:type_name -> graywolf.platform.UsbClass
	9,  // 32: graywolf.platform.UsbAttach.device:type_name -> graywolf.platform.UsbDevice
	1,  // 33: graywolf.platform.UsbDeviceListRequest.class_filter:type_name -> graywolf.platform.UsbClass
	9,  // 34: graywolf.platform.UsbDeviceListResponse.devices:type_name -> graywolf.platform.UsbDevice
	2,  // 35: graywolf.platform.PttKeyRequest.method:type_name -> graywolf.platform.PttMethod
	2,  // 36: graywolf.platform.PttUnkeyRequest.method:type_name -> graywolf.platform.PttMethod
	20, // 37: graywolf.platform.AudioDeviceListResponse.devices:type_name -> graywolf.platform.AudioDevice
	20, // 38: graywolf.platform.AudioRouteChanged.current_inputs:type_name -> graywolf.platform.AudioDevice
	20, // 39: graywolf.platform.AudioRouteChanged.current_outputs:type_name -> graywolf.platform.AudioDevice
	3,  // 40: graywolf.platform.Error.code:type_name -> graywolf.platform.ErrorCode
	24, // 41: graywolf.platform.GnssStatusUpdate.sats:type_name -> graywolf.platform.SatInfo
	4,  // 42: graywolf.platform.SerialOpen.kind:type_name -> graywolf.platform.SerialKind
	39, // 43: graywolf.platform.BondedBtDevicesResponse.devices:type_name -> graywolf.platform.BondedBtDevicesResponse.Device
	40, // 44: graywolf.platform.AvailableUsbSerialDevicesResponse.devices:type_name -> graywolf.platform.AvailableUsbSerialDevicesResponse.Device
	45, // [45:45] is the sub-list for method output_type
	45, // [45:45] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_platform_proto_init() }
func file_platform_proto_init() {
	if File_platform_proto != nil {
		return
	}
	file_platform_proto_msgTypes[0].OneofWrappers = []any{
		(*PlatformMessage_Hello)(nil),
		(*PlatformMessage_GpsFix)(nil),
		(*PlatformMessage_BatteryState)(nil),
		(*PlatformMessage_UsbAttach)(nil),
		(*PlatformMessage_UsbDetach)(nil),
		(*PlatformMessage_UsbListReq)(nil),
		(*PlatformMessage_UsbListResp)(nil),
		(*PlatformMessage_UsbSelectReq)(nil),
		(*PlatformMessage_UsbSelectResp)(nil),
		(*PlatformMessage_PttKeyReq)(nil),
		(*PlatformMessage_PttUnkeyReq)(nil),
		(*PlatformMessage_PttAck)(nil),
		(*PlatformMessage_AudioListReq)(nil),
		(*PlatformMessage_AudioListResp)(nil),
		(*PlatformMessage_AudioRouteChanged)(nil),
		(*PlatformMessage_Error)(nil),
		(*PlatformMessage_GnssStatus)(nil),
		(*PlatformMessage_SerialOpen)(nil),
		(*PlatformMessage_SerialOpenAck)(nil),
		(*PlatformMessage_SerialData)(nil),
		(*PlatformMessage_SerialClose)(nil),
		(*PlatformMessage_SerialError)(nil),
		(*PlatformMessage_BondedBtDevicesRequest)(nil),
		(*PlatformMessage_BondedBtDevicesResponse)(nil),
		(*PlatformMessage_AvailableUsbSerialDevicesRequest)(nil),
		(*PlatformMessage_AvailableUsbSerialDevicesResponse)(nil),
		(*PlatformMessage_BleScanRequest)(nil),
		(*PlatformMessage_BleScanResult)(nil),
		(*PlatformMessage_BleScanError)(nil),
		(*PlatformMessage_BleScanStop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_proto_rawDesc), len(file_platform_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_proto_goTypes,
		DependencyIndexes: file_platform_proto_depIdxs,
		EnumInfos:         file_platform_proto_enumTypes,
		MessageInfos:      file_platform_proto_msgTypes,
	}.Build()
	File_platform_proto = out.File
	file_platform_proto_goTypes = nil
	file_platform_proto_depIdxs = nil
}
